### ISSUE TITLE
建议保留原windows版本 对10个候选ip进行测速

### ISSUE THREAD

**Issue by h31105** [badafans/better-cloudflare-ip#1]
建议保留原windows版本 对10个候选ip进行测速
测试后发现当前linux版本仅选取一个“优选”ip进行测速，效果不太理想。

**Comment by badafans** [comment]
> 建议保留原windows版本 对10个候选ip进行测速
> 测试后发现当前linux版本仅选取一个“优选”ip进行测速，效果不太理想。

其实是对50个优选的IP进行测速的，你看到的最后的测速结果是50个优选的IP里面最快的那个二次测速，二次测速来保证50个测速筛选的结果的有效性。最终只列出一个IP是为了帮助很多选择困难症的人直接列出来最终的结果

**Comment by h31105** [comment]
我试了几次 选出来的IP都不太理想 
原来win版的方式 相对效率较高 基本上1-2次就可以得到比较理想的IP

**Comment by badafans** [comment]
> 我试了几次 选出来的IP都不太理想
> 原来win版的方式 相对效率较高 基本上1-2次就可以得到比较理想的IP

不应该的啊，我更新上传了windows版本，你可以测试看看。

**Comment by badafans** [comment]
> > 我试了几次 选出来的IP都不太理想
> > 原来win版的方式 相对效率较高 基本上1-2次就可以得到比较理想的IP
> 
> 不应该的啊，我更新上传了windows版本，你可以测试看看。



> 我试了几次 选出来的IP都不太理想
> 原来win版的方式 相对效率较高 基本上1-2次就可以得到比较理想的IP

加入电报群沟通吧 https://github.com/badafans/better-cloudflare-ip
