### ISSUE TITLE
能否添加设置使用自定义IP地址池

### ISSUE THREAD

**Issue by 201853910** [badafans/better-cloudflare-ip#100]
优选下载的IP地址池并不全面，有很多速度快的都没出现。  
是否可以添加读取txt文档检测，而不使用获取。  
或者自动检测所有公开IP池网段所有IP。  

举例：通过手动输入单IP测试，发现某个时间节点有个104.16.0.0这个速度还行，但是优选里面并没有。
单104.x里面就有104.16--104.27，所以有时候测速真的不是最快的那个

根据官方提供的IP池：https://www.cloudflare.com/zh-cn/ips/  
IPv4：
173.245.48.0/20
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
141.101.64.0/18
108.162.192.0/18
190.93.240.0/20
188.114.96.0/20
197.234.240.0/22
198.41.128.0/17
162.158.0.0/15
172.64.0.0/13
131.0.72.0/22
104.16.0.0/13
104.24.0.0/14
IPv6：
2400:cb00::/32
2606:4700::/32
2803:f800::/32
2405:b500::/32
2405:8100::/32
2a06:98c0::/29
2c0f:f248::/32
![image](https://user-images.githubusercontent.com/54168192/125797443-84bcb971-f808-4020-a007-4fa4a33fab7d.png)

**Comment by badafans** [comment]
IP池是由我这里统一维护的，我会定期更具不同运营商连接的机房特定下发所属的IP段

**Comment by taoqixfz** [comment]
定期是多久啊,我这边联通测找不到10兆

**Comment by taoqixfz** [comment]
> IP池是由我这里统一维护的，我会定期更具不同运营商连接的机房特定下发所属的IP段

定期是多久啊,我这边联通测找不到10兆

**Comment by taoqixfz** [comment]
> 优选下载的IP地址池并不全面，有很多速度快的都没出现。 是否可以添加读取txt文档检测，而不使用获取。 或者自动检测所有公开IP池网段所有IP。
> 
> 举例：通过手动输入单IP测试，发现某个时间节点有个104.16.0.0这个速度还行，但是优选里面并没有。 单104.x里面就有104.16--104.27，所以有时候测速真的不是最快的那个
> 
> 根据官方提供的IP池：https://www.cloudflare.com/zh-cn/ips/ IPv4： 173.245.48.0/20 103.21.244.0/22 103.22.200.0/22 103.31.4.0/22 141.101.64.0/18 108.162.192.0/18 190.93.240.0/20 188.114.96.0/20 197.234.240.0/22 198.41.128.0/17 162.158.0.0/15 172.64.0.0/13 131.0.72.0/22 104.16.0.0/13 104.24.0.0/14 IPv6： 2400:cb00::/32 2606:4700::/32 2803:f800::/32 2405:b500::/32 2405:8100::/32 2a06:98c0::/29 2c0f:f248::/32 ![image](https://user-images.githubusercontent.com/54168192/125797443-84bcb971-f808-4020-a007-4fa4a33fab7d.png)

感觉better并非是给大众使用的，不满足咱的需求，推荐使用https://ip.flares.cloud/和https://ip.flares.cloud/whole/进行测试。
