### ISSUE TITLE
系统无法接受输入的时间。

### ISSUE THREAD

**Issue by echosad** [badafans/better-cloudflare-ip#105]
![image](https://user-images.githubusercontent.com/89896030/131616957-0f9d28af-2a91-40f0-9401-9a72d3c8d1c2.png)

**Comment by badafans** [comment]
什么系统？

**Comment by 915880683** [comment]
win10  无法使用  提示如一楼的图

**Comment by badafans** [comment]
找到原因了  不要通过git下载，请下载release包。git下载的bat文件的编码是UTF8
