### ISSUE TITLE
openwrt bash 运行cf-openwrt.sh出现错误

### ISSUE THREAD

**Issue by eightsheep67** [badafans/better-cloudflare-ip#109]
curl: (6) Could not resolve host: 0.2;
Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
curl: (6) Could not resolve host: 0.2;
Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
curl: (6) Could not resolve host: 0.2;
Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.
curl: (6) Could not resolve host: 0.2;
curl: (6) Could not resolve host: 50%
Warning: Problem : timeout. Will retry in 1 seconds. 3 retries left.
curl: (6) Could not resolve host: 50%
Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
curl: (6) Could not resolve host: 50%
Warning: Problem : timeout. Will retry in 4 seconds. 1 retries left.

但是最终还是会继续运行，这个时哪里有问题吗？

**Comment by badafans** [comment]
加入telegram群组，详细排查问题  [https://t.me/better_cloudflare_ip](url)

**Comment by sxx1314** [comment]
能跑也无法测速，测完丢包之后直接gg然后循环测丢包。推荐会退到8月初的版本即可完美测速使用。

**Comment by badafans** [comment]
请使用最新shell版本
