### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by thiter** [badafans/better-cloudflare-ip#111]
$ sudo ./cf.sh 
Password:
请设置期望到 CloudFlare 服务器的带宽大小(单位 Mbps):30
DNS解析获取CF节点IP
######################################################################## 100.0%
发现新版本程序:
更新地址:
更新后才可以使用

-------------------------------------------------------------

sudo sh -x ./cf.sh 
+ declare -i bandwidth
+ declare -i speed
+ read -p '请设置期望到 CloudFlare 服务器的带宽大小(单位 Mbps):' bandwidth
请设置期望到 CloudFlare 服务器的带宽大小(单位 Mbps):30
+ speed='bandwidth*128*1024'
++ date '+%Y-%m-%d %H:%M:%S'
+ starttime='2021-09-13 20:55:52'
+ true
+ true
+ declare -i m
+ declare -i n
+ declare -i per
+ rm -rf icmp temp data.txt meta.txt log.txt anycast.txt temp.txt speed.txt
+ mkdir icmp
+ true
+ '[' -f resolve.txt ']'
+ echo $'DNS解?\236\220?\216??\217\226CF?\212\202?\202?IP'
DNS解析获取CF节点IP
+ true
+ '[' '!' -f meta.txt ']'
+ curl --ipv4 --retry 3 -s https://speed.cloudflare.com/meta
+ sed -e 's/{//g' -e 's/}//g' -e 's/"//g' -e 's/,/\n/g'
+ true
+ '[' '!' -f meta.txt ']'
++ cat meta.txt
++ grep asn:
++ awk -F: '{print $2}'
+ asn=speed.cloudflare.comnclientIp
++ cat meta.txt
++ grep city:
++ awk -F: '{print $2}'
+ city=speed.cloudflare.comnclientIp
++ cat meta.txt
++ grep latitude:
++ awk -F: '{print $2}'
+ latitude=speed.cloudflare.comnclientIp
++ cat meta.txt
++ grep longitude:
++ awk -F: '{print $2}'
+ longitude=speed.cloudflare.comnclientIp
+ curl --ipv4 --retry 3 'https://service.udpfile.com?asn=speed.cloudflare.comnclientIp&city=speed.cloudflare.comnclientIp' -o data.txt -#
######################################################################## 100.0%
+ break
+ '[' -f data.txt ']'
+ break
++ cat data.txt
++ grep domain=
++ cut -f 2- -d=
+ domain=
++ cat data.txt
++ grep file=
++ cut -f 2- -d=
+ file=
++ cat data.txt
++ grep url=
++ cut -f 2- -d=
+ url=
++ cat data.txt
++ grep app=
++ cut -f 2- -d=
+ app=
+ '[' '' '!=' 20210903 ']'
+ echo $'?\217\221?\216??\226??\211\210?\234??\213?\217:'
发现新版本程序:
+ echo $'?\233??\226??\234??\235\200:'
更新地址:
+ echo $'?\233??\226??\220\216?\211\215?\217?以使?\224?'
更新后才可以使用
+ exit
-------------------------------
thiter's macbook:shell thiter$ ping service.udpfile.com
PING service.udpfile.com (104.21.71.53): 56 data bytes
64 bytes from 104.21.71.53: icmp_seq=0 ttl=54 time=273.080 ms

**Comment by badafans** [comment]
mac没有测试环境，没有考虑苹果任何系列的适配

**Comment by scott-x** [comment]
@badafans 可以到linux机器里面去测试一下吗？一般linux能用，Mac就能用，谢谢！

**Comment by badafans** [comment]
linux肯定是测试通过的，我的树莓派以及Ubuntu的服务器都可以测试通过

**Comment by scott-x** [comment]
@badafans 刚才用树莓派测试了下 跑通了 非常感谢！

**Comment by thiter** [comment]
@badafans 我之前一直可以用。哈哈哈，这次更新完，就不可以用了。

**Comment by thiter** [comment]
@badafans 我换了一台mac，之前没有安装过脚本的机器，基本可以使用。我前些天提交的issue，是之前就在一直用，后来更新了。不能用了。我是重新./confirure && make .然后不能用了。

**Comment by thiter** [comment]
![image](https://user-images.githubusercontent.com/25921949/135036832-7180e7c2-b431-49e6-bc3c-5c671b316869.png)

**Comment by thiter** [comment]
按道理讲，在linux下可以用的话，mac也只是linux的其他发行版，哈哈哈

**Comment by badafans** [comment]
> 按道理讲，在linux下可以用的话，mac也只是linux的其他发行版，哈哈哈

是这样的，由于本人没有mac设备做测试，只能依赖网友反馈

**Comment by badafans** [comment]
最新的mac支持良好
