### ISSUE TITLE
请问openwrt版本的脚本在32位的CPU上能跑吗？

### ISSUE THREAD

**Issue by bluethief168** [badafans/better-cloudflare-ip#113]
20年前的古董Thinkpad X40，奔腾M，32位处理器，装了一个32位的openwrt做软路由，运行你的openwrt优选脚本，报错，有解决方案吗？

**Comment by badafans** [comment]
shell脚本与处理器架构关系不大，主要是你的运行环境里面配套的命令工具是不是gun标准工具

**Comment by bluethief168** [comment]
你是说GNU吧？我是小白，不懂怎么看是否安装了GNU，以及如何安装。能给个openwrt系统下安装GNU的教程链接吗？

**Comment by bluethief168** [comment]
https://support.huaweicloud.com/build-IDE-LiteOS/zh-cn_topic_0314196089.html
我如果按照这个教程来做，能成功吗？

**Comment by badafans** [comment]
> https://support.huaweicloud.com/build-IDE-LiteOS/zh-cn_topic_0314196089.html 我如果按照这个教程来做，能成功吗？

请使用Android Termux的版本
