### ISSUE TITLE
无法使用，打开优选IP.bat提示无法打开data.txt，但是目录下没有生成data.txt

### ISSUE THREAD

**Issue by cnmdbgcd** [badafans/better-cloudflare-ip#116]

**Comment by badafans** [comment]
近期阻断严重，很可能是服务器访问不了。三次重试后还是失败，导致无法下载ip地址

**Comment by paniy** [comment]
service.udpfile.com这个网站Access denied，屏蔽了大陆ip访问？

**Comment by badafans** [comment]
> service.udpfile.com这个网站Access denied，屏蔽了大陆ip访问？

禁止外部浏览器访问的，没有屏蔽大陆。防止各种垃圾数据干扰数据库。

**Comment by paniy** [comment]
> > service.udpfile.com这个网站Access denied，屏蔽了大陆ip访问？
> 
> 禁止外部浏览器访问的，没有屏蔽大陆。防止各种垃圾数据干扰数据库。

了解😅
