### ISSUE TITLE
mac已经下载最新的版本  一直提示更新才可以使用

### ISSUE THREAD

**Issue by samni728** [badafans/better-cloudflare-ip#118]
i$ ./cf.sh
请设置期望到 CloudFlare 服务器的带宽大小(单位 Mbps):50
DNS解析获取CF节点IP
######################################################################## 100.0%
发现新版本程序:
更新地址:
更新后才可以使用

**Comment by 0932test** [comment]
mac之前一直用得好好的，作者估计没有维护了。

**Comment by badafans** [comment]
新版本支持macos

**Comment by Skyellbin** [comment]
我最近几天也是这样呢
