### ISSUE TITLE
ip段好像不全

### ISSUE THREAD

**Issue by qzydustin** [badafans/better-cloudflare-ip#12]
cf官方的list https://www.cloudflare.com/ips-v4

例如162.158.0.0/15脚本到162.158.152就没有了，而且中间有跳过的

**Comment by badafans** [comment]
> cf官方的list https://www.cloudflare.com/ips-v4
> 
> 例如162.158.0.0/15脚本到162.158.152就没有了，而且中间有跳过的

有些不是anycast ip

**Comment by qzydustin** [comment]
> > cf官方的list https://www.cloudflare.com/ips-v4
> > 例如162.158.0.0/15脚本到162.158.152就没有了，而且中间有跳过的
> 
> 有些不是anycast ip

这个不是很懂，但是162.159.160.X 江苏移动速度很快
