### ISSUE TITLE
电信测速

### ISSUE THREAD

**Issue by KimiBear** [badafans/better-cloudflare-ip#122]
电信 测速IP每个好慢啊，筛选好久都出不来，大家一样吗？

**Comment by KimiBear** [comment]
第二次测试 104.16.135.7 不满足带宽需求,峰值速度 736 kB/s
第一次测试 104.25.94.82

每次测试速度都是几百KB 西安电信这几天一直这样！ 有一样的伙伴么

**Comment by badafans** [comment]
部分地区速度较慢
