### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by SuperReck** [badafans/better-cloudflare-ip#124]
启动CF优选IP.bat，窗口一直显示空白，文件夹内多出mate.txt文件和temp空文件夹，meta内显示的IP不能使用
![Uploading 1.png…]()

**Comment by KimiBear** [comment]
我最近也是，筛选不出IP，测速都是很慢的类似这样 
第一次测试 104.27.27.181 不满足带宽需求,峰值速度 471 kB/s
第二次测试 104.27.27.181
不知道怎么了

**Comment by badafans** [comment]
请更新最新版本试试

**Comment by SuperReck** [comment]
感谢作者！太棒了！！！
