### ISSUE TITLE
请问连不上service是什么原因

### ISSUE THREAD

**Issue by recmess** [badafans/better-cloudflare-ip#126]
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to service.udpfile.com:443

**Comment by badafans** [comment]
这个报错一半来自你的系统杀毒软件或者防火墙，给ssl证书屏蔽了

**Comment by recmess** [comment]
是有防火墙，我查一下是否屏蔽，请问另一半原因可能是什么？

**Comment by XuHuapeng001** [comment]
我家是直接用软路由翻墙的。
路由器上翻墙开启，可以正常运行"CF优选IP.bat"；路由器上关闭翻墙，有上述一样的问题。

大概半个月前还是好的；
家用的电脑和宽带，不存在防火墙的问题；win10系统，也没有装其他的杀毒软件。

**Comment by badafans** [comment]
> 我家是直接用软路由翻墙的。 路由器上翻墙开启，可以正常运行"CF优选IP.bat"；路由器上关闭翻墙，有上述一样的问题。
> 
> 大概半个月前还是好的； 家用的电脑和宽带，不存在防火墙的问题；win10系统，也没有装其他的杀毒软件。

此防火墙不是你想的那种防火墙，是一种更高级的防火墙，懂的都懂！

**Comment by badafans** [comment]
项目停止维护，被傻逼搞了，天天往接口里面发数据

**Comment by badafans** [comment]
后台服务已经恢复
