### ISSUE TITLE
提示更新才可以使用，但是本项目没有更新

### ISSUE THREAD

**Issue by chan1108** [badafans/better-cloudflare-ip#127]
![image](https://user-images.githubusercontent.com/54262303/146707708-02187b42-bf80-4237-aeb8-eb5a5b354879.png)

**Comment by badafans** [comment]
下载release版本使用

**Comment by leonsodey** [comment]
> 下载release版本使用

这就是Release版的提示，作者你运行程序测试下？

**Comment by badafans** [comment]
项目已经停止维护，被一个傻逼搞了，天天疯狂的往接口里面丢垃圾数据。

**Comment by zxy2012** [comment]
> 项目已经停止维护，被一个傻逼逼了，天天疯了的往接口里面丢垃圾数据。

草死他妈的狗日。我日他妈的。谁弄的

**Comment by l9rw** [comment]
谁这么傻X啊

**Comment by pprice2018** [comment]
难怪今天路由器里面跑不起来了，这傻逼真是日了狗了……

**Comment by badafans** [comment]
后台服务已经恢复
