### ISSUE TITLE
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.

### ISSUE THREAD

**Issue by linminning** [badafans/better-cloudflare-ip#129]
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.
Warning: Transient problem: timeout Will retry in 4 seconds. 1 retries left.

**Comment by badafans** [comment]
后台服务已经恢复
