### ISSUE TITLE
DNS解析获取CF ipv4 节点 如果域名被污染,请手动创建 ipv4.txt 做解析 curl: (35) OpenSSL SSL_connect: Connection was reset in connection to service.anycast.eu.org:443

### ISSUE THREAD

**Issue by earth-5G** [badafans/better-cloudflare-ip#134]
新版本出现问题

DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
curl: (35) OpenSSL SSL_connect: Connection was reset in connection to service.anycast.eu.org:443

我已经按照提示创建了txt，我也把dns改成119的那个了。还是没反应！

**Comment by badafans** [comment]
ipv4.txt里面需要填写内容 1.1.1.1

**Comment by earth-5G** [comment]
哦，谢谢！那个也没写呢！
