### ISSUE TITLE
不是很懂“自定义ipv4段”的意思。我以为是固定优选ip频段。比如我的优选ip一直是104.0.0.0频段的。然而这样设置之后一直无法优选成功

### ISSUE THREAD

**Issue by zhaoxumeng123** [badafans/better-cloudflare-ip#135]
RT。另外。如果我理解错。是否能添加上这个功能。另外。添加优选ping值小于某个数值才能speedtest。因为我这满足大于200Mbps的优选结果。一定是ping小于100ms。在104.0.0.0频段的ip。

**Comment by badafans** [comment]
移动用户才有可能低于100ms

**Comment by badafans** [comment]
自定义的意思是比如说，你输入104.16.16  实际测试的IP范围位 104.16.16.0-104.16.16.255
