### ISSUE TITLE
有没有arm版本？

### ISSUE THREAD

**Issue by kpking** [badafans/better-cloudflare-ip#137]
家里电脑不方便长时间开着，只能在路由器上运行了。

**Comment by qiumzh** [comment]
路由器也能跑，开少一点进程就好了

**Comment by kpking** [comment]
> 路由器也能跑，开少一点进程就好了

cf.sh: line 5: syntax error: unexpected "("
跑不了。出现这个错误

**Comment by kpking** [comment]
用bash运行。又出现这个错误……。
bash: ./cf.sh: /bin/bash: bad interpreter: No such file or directory

**Comment by kpking** [comment]
解决了。bash的路径错了
