### ISSUE TITLE
在梅林路由器上运行，报错curl: (7) Failed to connect to service.anycast.eu.org port 443: Connection timed out

### ISSUE THREAD

**Issue by kidxiang** [badafans/better-cloudflare-ip#139]
在联通宽带下报错：
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析

curl: (7) Failed to connect to service.anycast.eu.org port 443: Connection refused

在移动宽带下报错：
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析

curl: (7) Failed to connect to service.anycast.eu.org port 443: Connection timed out

**Comment by badafans** [comment]
先运行 echo 1.1.1.1>ipv4.txt   再运行脚本

**Comment by kidxiang** [comment]
谢谢，问题解决
