### ISSUE TITLE
最新版本报错提示无法打开cut.txt  无速度

### ISSUE THREAD

**Issue by Nicolas-Gong** [badafans/better-cloudflare-ip#145]
![image](https://user-images.githubusercontent.com/23067153/148888232-6b266a60-431d-420f-b29a-5737a06badc8.png)
系统 windows 10  运行 CF优选IP-UTF-8.bat

**Comment by badafans** [comment]
请使用release版本，并且确认你本地目录有CR2CRLF.exe的文件

**Comment by Nicolas-Gong** [comment]
> 

![image](https://user-images.githubusercontent.com/23067153/149105663-a65bbf27-0137-41b0-8e89-bceec4c44aba.png)
就是最新的啊。。。标题都写了最新呀，老哥

**Comment by Nicolas-Gong** [comment]
> 请使用release版本，并且确认你本地目录有CR2CRLF.exe的文件

![image](https://user-images.githubusercontent.com/23067153/149106099-3dcab5ef-b907-4219-aa97-c14c45cb7eed.png)
就是最新的啊。。。标题都写了最新呀，老哥

**Comment by badafans** [comment]
有没有办法提供一个环境做测试？

**Comment by Nicolas-Gong** [comment]
> 有没有办法提供一个环境做测试？

这。。。我咋提供呀？你加我tg吧，https://t.me/Nicholas_Gong
