### ISSUE TITLE
筛选的IP速度慢问题

### ISSUE THREAD

**Issue by KimiBear** [badafans/better-cloudflare-ip#147]
<img width="744" alt="微信图片_20220210143801" src="https://user-images.githubusercontent.com/23467996/153351610-915bac71-db40-4527-9855-b7d4acc71d8a.png">

线路电信，原来老版本筛选都是几百兆速度可以，后来新版本一直就是几百KB的速度了，请问是哪里需要调整优化吗？

**Comment by badafans** [comment]
最近CF在调整路由，整体的网络大环境都不好

**Comment by KimiBear** [comment]
好的，收到，但是感觉它这个调整周期蛮长的了。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "badafans/better-cloudflare-ip"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月11日(星期五) 中午12:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [badafans/better-cloudflare-ip] 筛选的IP速度慢问题 (Issue #147)





 
最近CF在调整路由，整体的网络大环境都不好

**Comment by Comah** [comment]
> 最近CF在调整路由，整体的网络大环境都不好
y已经一个多月都是这样了  不知道什么时候才能调整好
