### ISSUE TITLE
筛选的ip丢包严重 求解  有什么方法可以改善

### ISSUE THREAD

**Issue by samni728** [badafans/better-cloudflare-ip#149]
Request timeout for icmp_seq 77
64 bytes from 104.23.136.125: icmp_seq=78 ttl=55 time=183.099 ms
64 bytes from 104.23.136.125: icmp_seq=79 ttl=55 time=182.726 ms
64 bytes from 104.23.136.125: icmp_seq=80 ttl=55 time=182.316 ms
64 bytes from 104.23.136.125: icmp_seq=81 ttl=55 time=182.307 ms
64 bytes from 104.23.136.125: icmp_seq=82 ttl=55 time=183.190 ms
64 bytes from 104.23.136.125: icmp_seq=83 ttl=55 time=182.424 ms
64 bytes from 104.23.136.125: icmp_seq=84 ttl=55 time=183.234 ms
64 bytes from 104.23.136.125: icmp_seq=85 ttl=55 time=179.285 ms
Request timeout for icmp_seq 86
64 bytes from 104.23.136.125: icmp_seq=87 ttl=55 time=182.814 ms
64 bytes from 104.23.136.125: icmp_seq=88 ttl=55 time=182.629 ms
64 bytes from 104.23.136.125: icmp_seq=89 ttl=55 time=183.401 ms
64 bytes from 104.23.136.125: icmp_seq=90 ttl=55 time=183.138 ms
Request timeout for icmp_seq 91
64 bytes from 104.23.136.125: icmp_seq=92 ttl=55 time=183.363 ms
64 bytes from 104.23.136.125: icmp_seq=93 ttl=55 time=183.038 ms
^C
--- 104.23.136.125 ping statistics ---
94 packets transmitted, 76 packets received, 19.1% packet loss
round-trip min/avg/max/stddev = 174.292/182.214/190.279/2.255 ms

之前的版本 基本上都不回丢包 最近好像都不太好啊

**Comment by badafans** [comment]
最后一句话是对的  最近好像都不太好

**Comment by mivtec** [comment]
CMCC 到HKIX的线路都炸了
