### ISSUE TITLE
下的最新的，有乱码

### ISSUE THREAD

**Issue by lsh1215225** [badafans/better-cloudflare-ip#152]
![image](https://user-images.githubusercontent.com/20274559/153987554-c7a9b1df-d005-4fb7-b222-841118b6cf10.png)
有乱码

**Comment by xiaolong-chen** [comment]
![image](https://user-images.githubusercontent.com/54096964/154294414-901509c0-6031-4280-99dd-746d4ef664c9.png)
可以尝试 把第一句话注释掉，这个是调整编码的，不设定的话，走系统默认编码可能就不乱了，至少我去了就不乱了

**Comment by lsh1215225** [comment]
> ![image](https://user-images.githubusercontent.com/54096964/154294414-901509c0-6031-4280-99dd-746d4ef664c9.png) 可以尝试 把第一句话注释掉，这个是调整编码的，不设定的话，走系统默认编码可能就不乱了，至少我去了就不乱了

![image](https://user-images.githubusercontent.com/20274559/154425837-8a7c1ae6-7004-496e-b1db-4683b465770f.png)
还是不行

**Comment by xiaolong-chen** [comment]
> > ![image](https://user-images.githubusercontent.com/54096964/154294414-901509c0-6031-4280-99dd-746d4ef664c9.png) 可以尝试 把第一句话注释掉，这个是调整编码的，不设定的话，走系统默认编码可能就不乱了，至少我去了就不乱了
> 
> ![image](https://user-images.githubusercontent.com/20274559/154425837-8a7c1ae6-7004-496e-b1db-4683b465770f.png) 还是不行


:: 设置utf-8编码
@chcp 65001

936换成65001呢，这个是设置utf-8编码，一般而言，也就gbk和utf-8这两种编码了，gbk一般是默认的

**Comment by lsh1215225** [comment]
> > > ![image](https://user-images.githubusercontent.com/54096964/154294414-901509c0-6031-4280-99dd-746d4ef664c9.png) 可以尝试 把第一句话注释掉，这个是调整编码的，不设定的话，走系统默认编码可能就不乱了，至少我去了就不乱了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/20274559/154425837-8a7c1ae6-7004-496e-b1db-4683b465770f.png) 还是不行
> 
> :: 设置utf-8编码 @CHCP 65001
> 
> 936换成65001呢，这个是设置utf-8编码，一般而言，也就gbk和utf-8这两种编码了，gbk一般是默认的

![image](https://user-images.githubusercontent.com/20274559/154430338-9496826b-fe0a-48ed-94cc-038a5f6da606.png)
也不行hhh

**Comment by xiaolong-chen** [comment]
> > > ![image](https://user-images.githubusercontent.com/54096964/154294414-901509c0-6031-4280-99dd-746d4ef664c9.png) 可以尝试 把第一句话注释掉，这个是调整编码的，不设定的话，走系统默认编码可能就不乱了，至少我去了就不乱了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/20274559/154425837-8a7c1ae6-7004-496e-b1db-4683b465770f.png) 还是不行
> 
> :: 设置utf-8编码 @CHCP 65001
> 
> 936换成65001呢，这个是设置utf-8编码，一般而言，也就gbk和utf-8这两种编码了，gbk一般是默认的

![image](https://user-images.githubusercontent.com/54096964/154431486-f61c72d9-2766-4cfe-b463-4fcbabcdb2e4.png)
先看一下你系统的编码呢？

**Comment by xiaolong-chen** [comment]
> 
[CF优选IP.zip](https://github.com/badafans/better-cloudflare-ip/files/8086723/CF.IP.zip)
给你个我开始乱码，再我调了之后，我使用正常的bat文件吧，再乱我也不知道了，直接用也成，就是乱码不好看，程序还是能跑的

**Comment by lsh1215225** [comment]
> 

![image](https://user-images.githubusercontent.com/20274559/154441529-29e1f2a2-b21e-4ef0-8af6-d0b0d61cf546.png)
就是936  我先试下你下面发的hh

**Comment by lsh1215225** [comment]
> > 
> 
> [CF优选IP.zip](https://github.com/badafans/better-cloudflare-ip/files/8086723/CF.IP.zip) 给你个我开始乱码，再我调了之后，我使用正常的bat文件吧，再乱我也不知道了，直接用也成，就是乱码不好看，程序还是能跑的

![image](https://user-images.githubusercontent.com/20274559/154441825-82baf9cf-df3a-45ff-8eef-467481bbc4e1.png)
也是不行  感觉应该是我系统有问题

**Comment by badafans** [comment]
乱码大多数是windows的bug导致的

**Comment by tjxboy** [comment]
> ![image](https://user-images.githubusercontent.com/20274559/153987554-c7a9b1df-d005-4fb7-b222-841118b6cf10.png) 有乱码

我也有这个问题，前半边正常，后半边乱码。
然后我参照xiaolong-chen说的办法，把BAT里第一行的936换成65001还是不行。
但是，我然后再把BAT文件的编码转成UTF-8就好了。你试试我改的这个。
[CF优选IP-UTF8.zip](https://github.com/badafans/better-cloudflare-ip/files/8142173/CF.IP-UTF8.zip)

**Comment by lsh1215225** [comment]
> 乱码大多数是windows的bug导致的，有条件可以私信我提供调试环境看看到底是什么问题导致乱码
应该就是系统问题了，我在家虚拟机上用是正常的
