### ISSUE TITLE
改了DNS：119.29.29.29 仍然无法使用

### ISSUE THREAD

**Issue by zhaoyong0317** [badafans/better-cloudflare-ip#153]
1. IPV4优选
2. IPV6优选
3. 自定义IPV4段
4. 单IP测速
5. 清空缓存
0. 退出

请选择菜单:1
请设置期望的带宽大小(默认0,单位 Mbps):100
请设置RTT测试进程数(默认25,最大50):50
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
-#O=#   #    #
找不到文件 - IP.TXT
以零为除数的错误。
系统找不到文件 ip.txt。
找不到 D:\Software\v2ray\batch\ip.txt
RTT测试完成
当前所有IP都存在RTT丢包
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
-#O=#   #    #
找不到文件 - IP.TXT
以零为除数的错误。
系统找不到文件 ip.txt。
找不到 D:\Software\v2ray\batch\ip.txt
RTT测试完成
当前所有IP都存在RTT丢包
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
-#O=#   #    #
找不到文件 - IP.TXT
以零为除数的错误。
系统找不到文件 ip.txt。
找不到 D:\Software\v2ray\batch\ip.txt
RTT测试完成
当前所有IP都存在RTT丢包
DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
-=#=-#    #    #
找不到文件 - IP.TXT
以零为除数的错误。
系统找不到文件 ip.txt。
找不到 D:\Software\v2ray\batch\ip.txt
RTT测试完成
当前所有IP都存在RTT丢包

**Comment by badafans** [comment]
今天迁移后台服务器到guollme的2刀机，内存太小导致服务崩溃，现在已经恢复

**Comment by badafans** [comment]
清空缓存后再次尝试

**Comment by zhaoyong0317** [comment]
> 清空缓存后再次尝试

解决了 谢谢！
