### ISSUE TITLE
用这个找快IP导致我的网现在访问不到cloudflare代理的网站

### ISSUE THREAD

**Issue by chenmin1992** [badafans/better-cloudflare-ip#154]
如图
![image](https://user-images.githubusercontent.com/20168118/154789099-1e7de74c-5349-4006-aeb9-c4c80abed95b.png)

基本使用cloudflare的网站都访问不到了，超时，表现在104开头的IP上。

cloudflare上有没有页面解封一下？

或者其他方法

**Comment by badafans** [comment]
检查你的出站规则
