### ISSUE TITLE
termux输入链接无响应

### ISSUE THREAD

**Issue by Qingtian-creat** [badafans/better-cloudflare-ip#159]
在termux输入链接之后一直卡在rtt测试界面无响应![Screenshot_20220301_092645_com.termux_edit_12250122979900.jpg](https://user-images.githubusercontent.com/55982977/156087612-de66061c-8d93-40ca-a9bc-13b0854bbede.jpg)

**Comment by badafans** [comment]
确保ipv6的可用性再尝试
