### ISSUE TITLE
这个最新版本貌似不支持Win7环境

### ISSUE THREAD

**Issue by fenglianchen** [badafans/better-cloudflare-ip#160]
下载的最新版本，在win7本地环境双击自解压了curl.exe，点击运行，多个窗口弹出，良久也没有选出ip，设置10M都不行

**Comment by badafans** [comment]
windows 7下测试过，没问题的

**Comment by fenglianchen** [comment]
> windows 7下测试过，没问题的

**Comment by fenglianchen** [comment]
> windows 7下测试过，没问题的

兄弟，你帮我看下我这是啥情况呢？win7解压之后点开就是窗口乱跳，我用win10就没有这情况
https://v.douyu.com/show/85BAvqrJrJ17G4Lm

**Comment by badafans** [comment]
你的curl路径有问题  C:\User\Administrator\Downloads\batch\._cache_curl.exe ，应该是你的杀毒软件导致的

**Comment by fenglianchen** [comment]
> 你的curl路径有问题 C:\User\Administrator\Downloads\batch._cache_curl.exe ，应该是你的杀毒软件导致的

可我没安装杀毒软件呀？那应该怎么设置

**Comment by fenglianchen** [comment]
哦，我知道了，我把程序复制到非系统盘就可以正常运行了，不过还是没太明白，为什么程序在c盘就运行有问题
