### ISSUE TITLE
cloudflare betterip_当前所有IP都存在RTT丢包_ubuntu_shell

### ISSUE THREAD

**Issue by sam8816312** [badafans/better-cloudflare-ip#164]
同等网络下，windowns没有rtt丢包的问题，很快可以刷出最佳的IP，linux ubuntu shell 就是一直循环在rtt丢包，不知道是什么原因？我不才，看了一下代码，把如下
else
echo 当前所有IP都存在RTT丢包
tasknum=10
 这段给屏蔽了，但是好像没有效果，请大神指教，谢谢？

**Comment by the55555day** [comment]
我在旁路由测试中也出现Rtt全部丢包，手工指定ip绕过旁路由就好了

**Comment by sam8816312** [comment]
> 我猜你这种情况很可能是在你的虚拟机里面运行的

我是在树莓派里运行的，树莓派是ubuntu，但是rtt一直丢。网络是routeos路由器，但是出口什么的都没有做限制。用batch在windows里运行都是可以获取ip。百思不得其解。

**Comment by sam8816312** [comment]
> 我在旁路由测试中也出现Rtt全部丢包，手工指定ip绕过旁路由就好了
没有用旁路由，树莓派本来用作打印机服务器的。所有的dns 指向路由器。谢谢提醒，我用公网dns ，测试过了，也没有办法。看来可能是我的人品不佳。

**Comment by badafans** [comment]
目前最新版可以试下，数据库去除了大多数被SNI阻断的IP段
