### ISSUE TITLE
如何指定需要测速的节点列表

### ISSUE THREAD

**Issue by q345296237** [badafans/better-cloudflare-ip#165]
创建一个txt，放入要参与测速的节点，然后用命令指定它后测速。怎么操作？？？

**Comment by badafans** [comment]
这个请使用XIU2的https://github.com/XIU2/CloudflareSpeedTest

**Comment by q345296237** [comment]
> 这个请使用XIU2的https://github.com/XIU2/CloudflareSpeedTest

你的测速方式更加精准，所以想用你的方式去做，不能实现吗？

**Comment by badafans** [comment]
> 

有办法的，shell上实现比较容易，批处理CIDR子网比较麻烦
