### ISSUE TITLE
有个建议可以配置一个直接一键选V4和V6的版本默认最大线程

### ISSUE THREAD

**Issue by DifferentSparkler** [badafans/better-cloudflare-ip#166]
就是直接点击批处理就挑选出相应的地址 不用输入相关的设定
还有就是每次测试的结果直接输出以时间为名字的TXT结果到当前目录

**Comment by badafans** [comment]
自己稍微修改下脚本的参数就可以了，这个没必要作为公共的通用版本发布

**Comment by badafans** [comment]
主要问题还是在于我脚本里面没有任何注释，这样理解起来对初学者来说有一定的障碍

**Comment by DifferentSparkler** [comment]
> 主要问题还是在于我脚本里面没有任何注释，这样理解起来对初学者来说有一定的障碍

还有一点反馈一下 有时候运行了脚本 去干别的事情了  然后剪切板里面又放入了其它的数据  导致后面又要重新运行一次 所以还是建议 测试的结果直接输出以时间为名字的TXT结果到当前目录

**Comment by badafans** [comment]
> 

输出结果会在同级目录里面保存的，如果你选的是IPV4，在同一个目录里面有一个ipv4.txt的文件，打开文件就知道IP地址是啥了。ipv6同理

**Comment by DifferentSparkler** [comment]
> > 
> 
> 输出结果会在同级目录里面保存的，如果你选的是IPV4，在同一个目录里面有一个ipv4.txt的文件，打开文件就知道IP地址是啥了。ipv6同理

不好意思 以前用的时候没有注意  刚刚发现确实有的  可以让它完整的输出测试的结果到TXT里面最好带一个测试时间

**Comment by badafans** [comment]
> 

时间可以直接看系统修改日期的时间

**Comment by DifferentSparkler** [comment]
又学到一个小技巧
