### ISSUE TITLE
Ping doesn't pass

### ISSUE THREAD

**Issue by asterriya** [badafans/better-cloudflare-ip#169]
Ping of CF IP's doesn't pass in TM. Is there any idea how to make it work?

**Comment by badafans** [comment]
what is TM？

**Comment by asterriya** [comment]
> what is TM？

Turkmenistan

**Comment by badafans** [comment]
> > what is TM？
> 
> Turkmenistan

 Can ping pass any available CF ANYCAST IP‘s in TM？

**Comment by asterriya** [comment]
> > > what is TM？
> > 
> > 
> > Turkmenistan
> 
> Can ping pass any available CF ANYCAST IP‘s in TM？

Through your tool, it doesn't work at all. But though other, it's work. But when I paste CF IP into my V2ray config, it doesn't work. But ping still goes fine to the IP which other tool found to me.

**Comment by badafans** [comment]
> > > > what is TM？
> > > 
> > > 
> > > Turkmenistan
> > 
> > 
> > Can ping pass any available CF ANYCAST IP‘s in TM？
> 
> Through your tool, it doesn't work at all. But though other, it's work. But when I paste CF IP into my V2ray config, it doesn't work. But ping still goes fine to the IP which other tool found to me.

This tool ip delete 104.16.0.0/13 in my server database,This ip just adapt in China mainland network.There is no test network environment in TM,I'm sorry about that!

**Comment by asterriya** [comment]
What that mean? This 104.16.0.0/13 pass ping, but when I paste IP's from that range it's not working. And ping goes fine like 20-30ms.

**Comment by badafans** [comment]
> What that mean? This 104.16.0.0/13 pass ping, but when I paste IP's from that range it's not working. And ping goes fine like 20-30ms.

It's mean the api https://service.baipiaocf.ml to get ip's is igonore 104.16.0.0/13

**Comment by asterriya** [comment]
It doesn't work at all. Don't start to search any IPs and doesn't matter what range IP.

**Comment by badafans** [comment]
> V2ray config

confirm your  V2ray config or cloudflare dns config is right

**Comment by asterriya** [comment]
Yes, I checked and they are working. But when I paste IP's into address, it doesn't work. But ping goes smoothly. And your tool doesn't start to search IP's. I found IP through another one. I'm confused.

**Comment by badafans** [comment]
> Yes, I checked and they are working. But when I paste IP's into address, it doesn't work. But ping goes smoothly. And your tool doesn't start to search IP's. I found IP through another one. I'm confused.

maybe TM network tcp rst with CF IP's

**Comment by asterriya** [comment]
> > Yes, I checked and they are working. But when I paste IP's into address, it doesn't work. But ping goes smoothly. And your tool doesn't start to search IP's. I found IP through another one. I'm confused.
> 
> maybe TM network tcp rst with CF IP's,My tool work normal in any vps server,you can test it on http://hax.co.id

Of course. I'm not lying. So, why it's happening. Ping goes smoothly but when I use it as address then it's not pass traffic. So if ping goes, then my ISP doesn't block IP's

**Comment by badafans** [comment]
> 

Did you set the fake host in V2ray as your URL？

**Comment by asterriya** [comment]
Yes. I try to use WS path original. Try to use CF worker. Still no success. But before it's work with direct WS path generated by installation script and all goes smoothly.

**Comment by badafans** [comment]
> 

You can send me a vmess or vless link to test it out for you

**Comment by badafans** [comment]
> Yes. I try to use WS path original. Try to use CF worker. Still no success. But before it's work with direct WS path generated by installation script and all goes smoothly.

You can send me a vmess or vless link to test it out for you

**Comment by asterriya** [comment]
But you are not living in TM so for you, it will work for you, I'm sure. In China all CF working fine. Already ask my friend in China.

**Comment by badafans** [comment]
> But you are not living in TM so for you, it will work for you, I'm sure. In China all CF working fine. Already ask my friend in China.

Okay!
