### ISSUE TITLE
可以自定义ipv6区段吗

### ISSUE THREAD

**Issue by fredericky123** [badafans/better-cloudflare-ip#170]
谢谢！

**Comment by badafans** [comment]
ipv6地址太多了，以我服务器数据库为准，不提供客户端自定义

**Comment by fredericky123** [comment]
> ipv6地址太多了，以我服务器数据库为准，不提供客户端自定义
就是太多了 所以想自定义区段 方便迅速找到符合自己设定要求的
上午为了找符合要求的，扫了近一个小时
如果设置了自定义段 不就更快了么

**Comment by badafans** [comment]
20220615版本已经取消了自定义IP的功能，感觉没必要。要想自定义IP，不如去嫖中转IP

**Comment by fredericky123** [comment]
请问去哪里找中转IP?

**Comment by badafans** [comment]
> 请问去哪里找中转IP?

https://github.com/ip-scanner/cloudflare

**Comment by fredericky123** [comment]
感谢，我去看看
