### ISSUE TITLE
测速运行为何不停止？已经运行好几个小时了

### ISSUE THREAD

**Issue by cytown** [badafans/better-cloudflare-ip#174]
20220615版本

macos bigsur系统。

貌似陷入死循环了。

<img width="695" alt="image" src="https://user-images.githubusercontent.com/148625/194996492-a5b17164-e3b0-48d3-b937-356febee18cf.png">

<img width="638" alt="image" src="https://user-images.githubusercontent.com/148625/194996625-4b6dab89-f192-4ddd-9143-08f2fbe09359.png">

**Comment by badafans** [comment]
设定的期望带宽是多少，mac最新的系统我测试过没有问题的

**Comment by cytown** [comment]
> 设定的期望带宽是多少，mac最新的系统我测试过没有问题的

汗，是因为设置带宽太大的原因么？这个不应该是遍历然后排序就行么？

**Comment by badafans** [comment]
> 

带宽达不到就不会停止

**Comment by cytown** [comment]
修了一下：

https://github.com/badafans/better-cloudflare-ip/pull/175
