### ISSUE TITLE
能出个sh版本的吗，IOS的A-SHELL 不支持bash

### ISSUE THREAD

**Issue by MrYangJ** [badafans/better-cloudflare-ip#176]
IOS 的 a-shell只支持sh不支持bash 能力有限不知道如何转 大佬有考虑出个sh版本的脚本吗

**Comment by badafans** [comment]
ios使用ish，已经测试过没问题

**Comment by MrYangJ** [comment]
ish 需要添加两个命令才能用  apk add curl

**Comment by MrYangJ** [comment]
ish 需要添加两个命令才能用 
`apk add curl`

**Comment by MrYangJ** [comment]
ish 需要添加两个命令才能使用
`apk add curl`
`apk add bash`

**Comment by badafans** [comment]
> ish 需要添加两个命令才能使用 `apk add curl` `apk add bash`

这个我就不知道了，我没有iOS设备，都是别人给我测试后的结果

**Comment by MrYangJ** [comment]
> > ish 需要添加两个命令才能使用 `apk add curl` `apk add bash`
> 
> 这个我就不知道了，我没有iOS设备，都是别人给我测试后的结果

感谢作者，IOS16  我试了 安装这两个命令后    使用  bash  cf.sh 可以测试出优选IP来  大佬谢谢
