### ISSUE TITLE
一直提示Failed to connect to service.baipiaocf.ml，请问怎么回事呢？

### ISSUE THREAD

**Issue by Skyellbin** [badafans/better-cloudflare-ip#178]
Failed to connect to service.baipiaocf.ml

**Comment by badafans** [comment]
本周会发布离线版本，不需要服务端，敬请期待>>>

**Comment by dxmaimxd** [comment]
> 本周会发布离线版本，不需要服务端，敬请期待>>>

移动手机端使用ish   无法优选ipv6  求解决

**Comment by Skyellbin** [comment]
> 本周会发布离线版本，不需要服务端，敬请期待>>>

非常感谢！
