### ISSUE TITLE
mac这几天无法跑出优选ip，提示”发现新版本程序: 更新地址: 更新后才可以使用“

### ISSUE THREAD

**Issue by Skyellbin** [badafans/better-cloudflare-ip#179]
如果域名被污染,请手动创建 ipv4.txt 做解析
curl: (28) Operation timed out after 3004 milliseconds with 0 bytes received
Warning: Transient problem: timeout Will retry in 1 seconds. 1 retries left.
curl: (28) Failed to connect to service.baipiaocf.ml port 443: Operation timed out

DNS解析获取CF ipv4 节点
如果域名被污染,请手动创建 ipv4.txt 做解析
curl: (28) Operation timed out after 3002 milliseconds with 723 bytes received
Warning: Transient problem: timeout Will retry in 1 seconds. 1 retries left.
Throwing away 723 bytes
curl: (28) Operation timed out after 2002 milliseconds with 0 out of 0 bytes received

发现新版本程序:
更新地址:
更新后才可以使用

**Comment by badafans** [comment]
服务端TLS阻断严重，本周会发布离线版本，不需要服务端。敬请期待>>>

**Comment by dxmaimxd** [comment]
> 服务端TLS阻断严重，本周会发布离线版本，不需要服务端。敬请期待>>>

移动手机端使用ish 无法优选ipv6 求解决

**Comment by badafans** [comment]
> 

试试新版，用非TLS选项
