### ISSUE TITLE
当前所有IP都存在RTT丢包

### ISSUE THREAD

**Issue by brightu** [badafans/better-cloudflare-ip#183]
运行了很多次,总是提示"当前所有IP都存在RTT丢包"

已经提前清理缓存了,还是不行,刷不出来ip

继续新的RTT测试
正在生成 ipv6
16:56:54 等待RTT测试结束,剩余进程数 10
16:56:55 等待RTT测试结束,剩余进程数 10
16:56:56 RTT测试完成
当前所有IP都存在RTT丢包
继续新的RTT测试
正在生成 ipv6
16:56:57 等待RTT测试结束,剩余进程数 10
16:56:58 RTT测试完成
当前所有IP都存在RTT丢包
继续新的RTT测试
正在生成 ipv6
16:56:59 等待RTT测试结束,剩余进程数 10
16:57:00 等待RTT测试结束,剩余进程数 9
16:57:01 RTT测试完成
当前所有IP都存在RTT丢包
继续新的RTT测试
正在生成 ipv6
16:57:02 等待RTT测试结束,剩余进程数 10
16:57:03 等待RTT测试结束,剩余进程数 10
16:57:04 RTT测试完成
当前所有IP都存在RTT丢包
继续新的RTT测试
正在生成 ipv6
16:57:05 等待RTT测试结束,剩余进程数 10
16:57:06 等待RTT测试结束,剩余进程数 2
16:57:07 RTT测试完成
当前所有IP都存在RTT丢包
继续新的RTT测试
正在生成 ipv6
16:57:08 等待RTT测试结束,剩余进程数 10
16:57:09 等待RTT测试结束,剩余进程数 10
16:57:10 RTT测试完成
当前所有IP都存在RTT丢包
继续新的RTT测试
正在生成 ipv6
16:57:11 等待RTT测试结束,剩余进程数 10
16:57:12 等待RTT测试结束,剩余进程数 3
16:57:13 RTT测试完成
当前所有IP都存在RTT丢包
继续新的RTT测试
正在生成 ipv6

**Comment by badafans** [comment]
请确保你本地能访问IPV6网络，你这个状态一看就知道访问不了IPV6

**Comment by brightu** [comment]
谢谢提醒，确实如此。
