### ISSUE TITLE
Alternative for Gcore

### ISSUE THREAD

**Issue by Stevemoretz** [badafans/better-cloudflare-ip#187]
Gcore provides the same features as cloudflare, the list of its ip addresses are here: https://gcore.com/support/articles/360000208709/

Is it easy to make this script work for that as well? Or is it too different?

**Comment by badafans** [comment]
92.223.118.39
5.188.121.192
92.223.124.23
92.223.12.17
92.223.68.25
92.223.123.101
92.223.118.10
92.38.159.5
92.223.107.40
92.223.126.52
92.223.107.36
92.223.118.17
92.223.124.31
31.184.207.5
92.223.107.58
92.223.107.43
5.189.207.5
94.176.183.7
92.223.107.57
93.123.38.4
87.120.106.5
92.223.126.33
103.211.151.21
92.223.123.36
31.184.207.6
181.174.80.182
80.93.221.4
92.223.124.28
82.114.163.146
213.156.144.6
92.223.47.4
92.223.126.28
79.133.108.15
92.223.78.22
92.223.107.56
92.223.107.42
92.223.61.23
5.189.207.4
213.248.88.81
92.223.126.31
5.8.43.5
213.156.151.6
92.223.12.10
5.8.43.4
92.223.63.9
92.223.120.14
31.184.207.8
134.0.219.26
5.101.222.4
186.16.19.94
92.223.108.16
92.223.124.40
5.188.121.185
92.223.116.201
178.22.172.254
92.223.63.26
185.194.11.74
92.223.12.5
92.223.124.26
92.223.126.18
92.223.124.39
92.223.76.24
92.223.63.7
92.223.116.207
92.223.126.55
185.101.136.12
79.133.108.8
195.22.198.49
92.223.116.216
37.110.209.228
92.223.123.32
92.223.123.51
92.223.12.22
92.223.76.23
92.223.12.13
95.85.93.4
92.223.64.8
92.223.12.11
92.223.124.35
150.107.126.4
92.223.107.46
92.223.123.46
5.188.121.151
80.240.124.5
92.223.123.40
92.223.126.42
92.223.76.25
92.223.116.222
185.188.144.5
5.252.26.6
109.230.114.2
92.223.126.51
5.188.121.180
92.223.126.49
92.223.63.21
92.223.12.12
92.223.12.24
92.223.92.24
92.223.55.6
92.223.123.10
92.223.123.41
92.223.116.212
80.240.124.6
79.133.108.14
92.223.118.15
92.223.68.26
92.223.92.26
89.218.28.25
45.82.101.7
92.223.107.47
92.223.116.209
5.1.106.249
92.223.74.26
185.105.1.10
92.223.122.172
92.223.64.12
92.223.124.9
95.85.88.9
167.160.20.173
5.188.7.12
185.188.144.4
93.123.38.5
213.156.151.4
81.253.239.2
5.188.121.191
102.68.141.74
92.223.12.16
92.223.126.36
92.223.74.21
185.101.136.8
82.97.205.4
5.188.121.179
92.223.108.13
92.223.63.22
92.223.116.204
92.223.107.45
92.223.118.16
5.252.26.4
92.223.114.6
95.85.88.8
92.223.12.9
95.85.92.7
80.240.113.4
92.223.107.50
185.211.231.195
81.253.239.38
92.223.124.36
92.223.123.33
92.223.126.41
92.223.107.44
5.101.219.5
92.38.170.10
92.223.126.38
92.38.142.22
92.223.63.28
130.193.166.2
5.252.26.8
80.240.124.9
92.223.116.203
176.222.188.242
92.223.114.7
45.82.103.7
92.223.12.23
45.82.101.6
171.229.196.133
92.223.126.53
78.111.103.4
171.234.242.198
92.223.12.14
92.223.124.32
188.94.153.2
5.188.121.181
92.223.123.15
171.229.196.134
171.229.196.135
92.223.107.51
92.223.108.14
92.223.126.26
91.243.87.5
151.248.104.95
92.38.168.7
134.0.219.37
92.38.159.4
80.240.113.7
87.120.164.7
92.223.116.211
92.38.168.5
93.123.11.14
181.39.11.210
79.133.108.17
79.133.108.4
92.223.116.214
5.188.121.166
80.240.113.6
5.252.26.5
171.234.242.199
171.229.196.138
5.188.121.165
5.188.132.5
92.223.123.30
92.223.107.53
5.101.68.8
5.101.217.4
92.223.107.55
92.223.68.22
78.111.101.4
92.223.12.19
92.223.118.24
92.223.124.34
92.223.118.19
79.133.108.7
92.223.12.6
92.223.63.24
95.85.92.4
92.223.63.23
5.188.121.182
93.123.11.12
5.101.68.10
92.223.126.19
92.223.120.15
92.223.126.45
80.240.124.7
92.223.116.221
82.213.5.50
31.184.207.4
80.240.113.9
92.223.110.4
213.156.144.5
5.188.126.5
5.8.92.4
37.17.119.116
92.223.126.37
91.243.87.4
46.49.10.229
92.223.124.13
92.223.63.11
5.101.222.5
92.223.120.13
92.223.126.48
92.223.123.34
92.223.124.30
212.188.76.67
92.223.124.25
92.223.64.4
87.120.106.10
217.76.64.90
92.223.118.40
80.240.124.8
92.223.123.20
5.8.92.5
92.223.116.210
95.85.69.7
92.223.123.45
92.223.78.23
92.223.124.38
92.223.122.169
92.223.116.206
185.54.255.251
5.188.133.10
92.223.120.12
92.223.124.5
95.85.92.8
45.82.103.6
92.223.124.4
92.223.126.29
92.223.118.38
79.133.108.6
92.223.124.6
92.223.124.27
92.223.124.37
170.238.234.217
92.223.68.27
92.223.118.26
92.223.92.25
31.184.207.7
5.8.43.6
5.188.94.5
92.223.122.188
92.223.112.28
92.223.126.21
92.223.63.4
5.188.126.6
92.223.116.224
79.133.108.9
81.253.239.14
194.44.246.206
94.176.183.8
194.152.37.181
92.223.118.23
92.223.126.59
5.188.121.132
92.223.107.48
92.223.63.10
5.188.7.13
87.120.106.4
92.223.43.12
92.223.12.4
45.82.103.4
92.223.108.15
5.188.126.7
80.240.124.4
92.223.124.33
92.38.142.20
92.223.124.41
79.133.108.13
92.223.116.213
87.120.164.6
92.223.126.32
92.223.63.25
212.188.31.71
92.38.168.6
95.85.92.6
180.149.90.66
91.243.83.5
92.223.63.6
92.223.120.10
95.85.92.5
92.223.123.47
92.223.118.37
92.223.118.8
80.240.113.8
92.223.92.22
92.223.116.215
92.223.112.12
5.188.121.162
92.223.126.47
5.188.121.137
43.245.140.2
92.223.118.22
92.223.126.46
92.223.122.186
185.101.137.10
92.223.107.52
5.8.92.6
92.223.126.22
92.223.122.171
92.223.126.34
92.223.64.10
37.17.119.115
37.98.156.190
92.223.116.205
46.19.99.6
95.85.69.6
188.72.125.12
102.130.69.141
92.223.126.24
92.223.108.7
94.128.12.238
146.185.221.132
92.223.126.27
120.28.10.46
185.101.136.9
92.223.118.25
79.133.108.5
92.223.126.35
79.133.108.16
92.38.142.25
171.234.242.195
92.223.124.42
92.223.43.14
92.223.126.23
92.38.170.6
92.223.126.44
82.97.205.5
92.223.122.185
195.14.146.81
193.251.143.79
82.148.98.42
92.223.123.50
45.82.100.4
92.38.170.8
5.188.133.11
92.223.124.29
92.223.122.187
37.17.119.114
92.223.126.54
92.223.126.30
92.223.124.12
185.163.3.4
93.123.11.11
92.223.107.49
5.101.68.5
92.223.126.25
92.223.122.170
92.223.123.12
37.236.95.2
92.223.61.21
80.240.113.5
92.223.116.220
45.82.103.5
92.223.118.14
45.82.101.5
89.223.90.4
5.188.121.136
5.188.121.138
92.223.126.40
45.65.8.4
92.223.43.13
171.229.196.137
93.123.11.13
92.223.118.20
5.188.121.184
190.95.248.34
197.215.140.234
92.223.122.177
92.223.114.11
179.0.200.101
92.223.116.208
217.21.47.162
92.223.116.223
87.120.164.5
92.223.124.10
185.101.136.13
5.188.121.163
78.111.103.5
109.68.233.242
92.223.76.20
92.223.63.27
77.79.161.54
92.223.116.200
5.188.121.134
188.94.153.3
92.223.122.173
171.229.196.132
92.38.142.23
87.120.106.11
213.156.151.5
92.223.107.38
92.223.114.14
92.223.12.15
92.223.92.23
5.101.219.6
92.38.142.24
5.188.121.161
217.118.183.250
178.160.192.38
92.223.122.184
92.223.12.8
92.223.63.29
92.223.123.100
92.223.126.50
92.223.126.20
79.133.108.10
171.234.242.197
92.223.118.21
92.223.107.54
195.34.58.19
92.223.124.15
87.120.106.8
213.156.144.7
92.223.124.8
92.223.118.27
92.223.107.39
92.223.63.8
5.252.26.7
87.120.164.4
92.223.74.20
92.223.55.4
92.223.123.11
92.38.170.7
5.188.121.133
92.223.123.48
92.223.63.5
91.243.83.4
94.176.183.5
185.158.211.186
92.223.126.39
92.223.55.5
171.229.196.136
62.209.27.232
94.176.183.6
5.188.121.178
5.188.121.183
213.156.144.4
5.188.121.135
92.223.12.7
195.34.58.17
92.223.108.5
92.223.108.6
185.101.136.7
92.38.142.21

**Comment by badafans** [comment]
gcore cdn cannot use cdn trace to track return information, so this project script cannot be used for gcore.
