### ISSUE TITLE
双击bat文件没有反应

### ISSUE THREAD

**Issue by 8ty** [badafans/better-cloudflare-ip#188]
win11 已经自带curl
双击bat文件没有反应，两个都试过了，也已经用管理员试过，均无反应

**Comment by badafans** [comment]
> 

有没有可能是windows 安全策略阻止了bat运行？

**Comment by 8ty** [comment]
> 

那请问要怎么解决呢？我试了一下其他的bat文件是可以打开的

**Comment by badafans** [comment]
> > 
> 
> 那请问要怎么解决呢？我试了一下其他的bat文件是可以打开的

https://t.me/better_cloudflare_ip 加入群组，反馈使用问题

**Comment by 8ty** [comment]
> > > 
> > 
> > 
> > 那请问要怎么解决呢？我试了一下其他的bat文件是可以打开的
> 
> https://t.me/better_cloudflare_ip 加入群组，反馈使用问题

好的，感谢
