### ISSUE TITLE
撞车项目发来贺电~ 这是我发现的第三个撞车项目了 😂。。。互相交流！

### ISSUE THREAD

**Issue by XIU2** [badafans/better-cloudflare-ip#19]
在 Github 的海洋里不知道有多少项目撞车了，有需求的时候怎么搜也搜不到，自己造出来后发现又重复造轮子了。。。  
这已经是我在 Explore 推荐列表里看到的**第三个同类撞车项目**了！  

* **https://github.com/XIU2/CloudflareSpeedTest**  

> 看了下，咱们两个的项目功能都差不多，主要是开发语言的差别，我用的是 Golang ...  

同类项目 互相交流~

**Comment by badafans** [comment]
> 在 Github 的海洋里不知道有多少项目撞车了，有需求的时候怎么搜也搜不到，自己造出来后发现又重复造轮子了。。。
> 这已经是我在 Explore 推荐列表里看到的**第三个同类撞车项目**了！
> 
> * **https://github.com/XIU2/CloudflareSpeedTest**
> 
> > 看了下，咱们两个的项目功能都差不多，主要是开发语言的差别，我用的是 Golang ...
> 
> 同类项目 互相交流~

我对编程不太懂，只会一些脚本语言

**Comment by badafans** [comment]
> 在 Github 的海洋里不知道有多少项目撞车了，有需求的时候怎么搜也搜不到，自己造出来后发现又重复造轮子了。。。
> 这已经是我在 Explore 推荐列表里看到的**第三个同类撞车项目**了！
> 
> * **https://github.com/XIU2/CloudflareSpeedTest**
>   _🌩 测试 Cloudflare CDN 所有 IP 的延迟和速度，获取最快 IP！_
> 
> > 看了下，咱们两个的项目功能都差不多，主要是开发语言的差别，我用的是 Golang，只有一个执行文件，不需要依赖...
> 
> 同类项目 互相交流~

我看了你的go项目，总体来说还不错，待改进的地方也很多。

**Comment by XIU2** [comment]
> 我看了你的go项目，总体来说还不错，待改进的地方也很多。

主要是因为我是为了满足自己的需求而**临时学的 Golang**，我平时会因为自己的各种各样的需求而**业余自学很多语言**，当然一般实现需求后我就**没动力继续向下学习了**。。。

**Comment by badafans** [comment]
> > 我看了你的go项目，总体来说还不错，待改进的地方也很多。
> 
> 主要是因为我是为了满足自己的需求而**临时学的 Golang**，我平时会因为自己的各种各样的需求而**业余自学很多语言**（一旦网上找不到满意的，我就会自己选个合适的语言去实现），当然一般实现需求后我就**没动力继续向下学习了**...
> 
> 所以就是**杂而不精**，都只能算**业余入门水平**，主要用来实现**个人小需求**。

go我也学了一些，跨平台交叉编译是他的绝对优势。此项目用脚本语言是为了获得更好的扩展。我的早期版本是https://github.com/CCChieh/IBMYes/tree/master/fping-msys2.0 后来考虑到还不够傻瓜化和多平台支持，后续开发了此项目。

**Comment by XIU2** [comment]
是啊，之所以选 Go 除了跨平台支持很棒外，主要是其在**网络领域**占有很大优势，且**并行效率**也非常高，所以用来批量测速 CF IP 感觉非常契合！

**Comment by XIU2** [comment]
我看你更换了自建的 Cloudflare 下载测速地址，你这个图片文件 CDN 缓存命中率怎么样，Cloudflare 获取一次后是不是就不会再去访问源站了？我也考虑过自建，但是不清楚 Cloudflare 会不会频繁访问源站，这样可能会太消耗服务器流量。  

另外，Cloudflare 免费版似乎有 10TB 的流量上限？（前几天查的时候看别人说的，应该不会完全无限，但是不知道多少）

**Comment by badafans** [comment]
> 我看你更换了自建的 Cloudflare 下载测速地址，你这个图片文件 CDN 缓存命中率怎么样，Cloudflare 获取一次后是不是就不会再去访问源站了？我也考虑过自建，但是不清楚 Cloudflare 会不会频繁访问源站，这样可能会太消耗服务器流量。
> 
> 另外，Cloudflare 免费版似乎有 10TB 的流量上限？（前几天查的时候看别人说的，应该不会完全无限，但是不知道多少）

cf管理页面上设置号以后回源的数据几乎没有，另外cf是无限流量的，不存在10TB的说法

**Comment by XIU2** [comment]
你的 Cloudflare Analytics 流量统计里，有没有 [未缓存的带宽]，我这边看总有一小部分未缓存的，不知道是啥意思。

**Comment by badafans** [comment]
少量的正常的。不可能完全不回源

**Comment by XIU2** [comment]
我查了查，在 Cloudflare 添加了一个页面规则：

主要是第三条，看官网文档说的是：**“这将控制我们在缓存中保留文件的时长。”**  

又查了下，看别人也是说这是用来**控制回源频率**的，这样应该就不会频繁回源了，虽然现在还看不出什么，特地发给你参考一下。  

![1](https://user-images.githubusercontent.com/54703944/98465750-1016a600-2206-11eb-8794-a7ceef56b25a.png)

**Comment by badafans** [comment]
> 我查了查，在 Cloudflare 添加了一个页面规则：
> 
> 主要是第三条，看官网文档说的是：**“这将控制我们在缓存中保留文件的时长。”**
> 
> 又查了下，看别人也是说这是用来**控制回源频率**的，这样应该就不会频繁回源了，虽然现在还看不出什么，特地发给你参考一下。
> 
> ![1](https://user-images.githubusercontent.com/54703944/98465750-1016a600-2206-11eb-8794-a7ceef56b25a.png)

看来你对网络知识不太懂，自己去看看边缘缓存是怎么个原理吧

**Comment by XIU2** [comment]
好吧，我也只是业余的，是我多嘴了。  

我只是意外看到[官方原话](https://support.cloudflare.com/hc/zh-cn/articles/218411427)：
“通过 Page Rule 指定缓存级别时，您可以选择设置edge cache TTL，这将控制我们在缓存中保留文件的时长。”  

可能是我理解错了，溜了溜了。。。

**Comment by XIU2** [comment]
问下，你自建的下载测速地址每个月流量消耗如何（CDN 缓存流量）？  

主要是我在 [Cloudflare 服务条款](https://www.cloudflare.com/zh-cn/terms/)中看到了这个：

```
# 翻译

2.8提供非HTML内容的限制
服务主要是作为缓存和服务网页和网站的平台提供的。除非明确包含在您购买的付费服务中，否则您同意仅将服务用于以下目的：
（i）提供通过网络浏览器或其他功能等效的应用程序（包括呈现超文本标记语言（HTML））查看的网页或其他等效功能，以及
（ii）根据第2.8节规定的限制提供网络API。禁止将服务用于提供视频或不成比例的图片，音频文件或其他非HTML内容，除非作为付费服务的一部分单独购买或根据我们的补充条款明确允许特定服务。如果我们确定您违反了第2.8节，我们可能会立即暂停或限制您对服务的使用，或限制最终用户通过服务访问您的某些资源。

# 原文

2.8 Limitation on Serving Non-HTML Content
The Services are offered primarily as a platform to cache and serve web pages and websites. Unless explicitly included as part of a Paid Service purchased by you, you agree to use the Services solely for the purpose of 
(i) serving web pages as viewed through a web browser or other functionally equivalent applications, including rendering Hypertext Markup Language (HTML) or other functional equivalents, and 
(ii) serving web APIs subject to the restrictions set forth in this Section 2.8. Use of the Services for serving video or a disproportionate percentage of pictures, audio files, or other non-HTML content is prohibited, unless purchased separately as part of a Paid Service or expressly allowed under our Supplemental Terms for a specific Service. If we determine you have breached this Section 2.8, we may immediately suspend or restrict your use of the Services, or limit End User access to certain of your resources through the Services.
```

不知道我们这样用算不算违反服务条款。。。

**Comment by badafans** [comment]
你现在一个月消耗多少CF流量

**Comment by XIU2** [comment]
Cloudflare 提供的 Analytics 中显示的 30天 是 9TB。

**Comment by badafans** [comment]
应该没啥问题，我的流量总带宽上个月125.66 TB

**Comment by XIU2** [comment]
那我就放心了！谢啦😆

**Comment by XIU2** [comment]
话说，你现在的 **CDN 缓存流量**有多少了？

我的显示 30 天是 77 TB 了。

特别是最近几天不知道什么情况，突然日缓存从 2 TB 增加到了 5 TB，如果一直保持这样的话，岂不是一个月要 150 TB 了？
所以想问问你的情况，主要是担心被 Cloudflare 限制。。。

> 奇怪的是，虽然日缓存流量暴增，但是日请求数却涨幅不大（虽然也是上涨的，但也没那么大幅度），不知道什么情况。。。

**Comment by badafans** [comment]
不限流量，我一个月接近300T

**Comment by XIU2** [comment]
OK！看来是我多虑了~
