### ISSUE TITLE
The process tried to write to a nonexistent pipe.

### ISSUE THREAD

**Issue by fjweel** [badafans/better-cloudflare-ip#190]
运行后出现The process tried to write to a nonexistent pipe.
不知是什么原因

**Comment by badafans** [comment]
请更换你的ssh客户端再重试，推荐使用putty

**Comment by fjweel** [comment]
使用的是win版，直接运行“CF优选IP-UTF8”

**Comment by fjweel** [comment]
> 使用的是win版，直接运行“CF优选IP-UTF8”

可能是环境变量的问题？
