### ISSUE TITLE
IPV4优选(TLS) 和IPV4优选有什么区别？

### ISSUE THREAD

**Issue by gc89925** [badafans/better-cloudflare-ip#193]
小白一枚，
用的windows离线版，
使用环境是：unraid下虚拟的openwrt,网口做了直通，
如果选IPV4优选(TLS)测试，显示的都是--当前所有IP都存在RTT丢包，然后不停重复
选IPV4优选就是正常的可以得到结果

**Comment by badafans** [comment]
TLS优选就是通过HTTPS测试URL，目前国内CF IP的TLS传输会被阻断，所以就会产生当前所有IP都存在RTT丢包。目前直接用选项2即可
