### ISSUE TITLE
优选的ip连不上warp+ 

### ISSUE THREAD

**Issue by vitock** [badafans/better-cloudflare-ip#196]
![image](https://user-images.githubusercontent.com/6203946/235052013-62af37dc-ced3-4118-ae49-397e9ddc3e78.png)

测试速度很快，但是连不上warp+ ？

**Comment by badafans** [comment]
这个跟warp+没有任何关联

**Comment by vitock** [comment]
> 这个跟warp+没有任何关联

我用其他地方找到的 warp+ 的ip地址，然后用你这个代码测试，效果不错
