### ISSUE TITLE
windows10自动查找没有结果

### ISSUE THREAD

**Issue by huzy0909** [badafans/better-cloudflare-ip#2]
windows10下使用，生成IP.txt为空，生成temp文件夹闪了一下，就没有了，curl已安装好，谢谢作者！
对话框显示为：

优选的CF地址为 2807
3秒后对 2807 进行20秒测速
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 吊销功能无法检查证书是否吊销。
测速结果自己判断是否满意,如果不满意,再来一遍
请按任意键继续. . .

**Comment by badafans** [comment]
> windows10下使用，生成IP.txt为空，生成temp文件夹闪了一下，就没有了，curl已安装好，谢谢作者！
> 对话框显示为：
> 
> 优选的CF地址为 2807
> 3秒后对 2807 进行20秒测速
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
> curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 吊销功能无法检查证书是否吊销。
> 测速结果自己判断是否满意,如果不满意,再来一遍
> 请按任意键继续. . .

Windows 10已经自带curl了，我这个程序目录下不要放第三方编译的curl进去，因为第三方curl需要https证书，所以你删除同目录下的curl再测试看看

**Comment by huzy0909** [comment]
我是在https://curl.haxx.se/download.html下载了一个curl文件，放在了D盘，加入了环境变量，我把CURL文件夹删除，环境变量也删除，重启电脑后，依然不行，随机显示下面2种结果。

优选的CF地址为 2807
3秒后对 2807 进行20秒测速
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (28) Operation timed out after 2000 milliseconds with 0 out of 0 bytes received
测速结果自己判断是否满意,如果不满意,再来一遍
请按任意键继续. . .

===============================
优选的CF地址为 2807
3秒后对 2807 进行20秒测速
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 吊销功能无法检查证书是否吊销。
测速结果自己判断是否满意,如果不满意,再来一遍
请按任意键继续. . .

**Comment by badafans** [comment]
> 我是在https://curl.haxx.se/download.html下载了一个curl文件，放在了D盘，加入了环境变量，我把CURL文件夹删除，环境变量也删除，重启电脑后，依然不行，随机显示下面2种结果。
> 
> 优选的CF地址为 2807
> 3秒后对 2807 进行20秒测速
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
> curl: (28) Operation timed out after 2000 milliseconds with 0 out of 0 bytes received
> 测速结果自己判断是否满意,如果不满意,再来一遍
> 请按任意键继续. . .
> 
> ===============================
> 优选的CF地址为 2807
> 3秒后对 2807 进行20秒测速
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 吊销功能无法检查证书是否吊销。
> 测速结果自己判断是否满意,如果不满意,再来一遍
> 请按任意键继续. . .
> 

晚点我建个电报群沟通一下，你这个肯定是curl的问题

**Comment by badafans** [comment]
> 我是在https://curl.haxx.se/download.html下载了一个curl文件，放在了D盘，加入了环境变量，我把CURL文件夹删除，环境变量也删除，重启电脑后，依然不行，随机显示下面2种结果。
> 
> 优选的CF地址为 2807
> 3秒后对 2807 进行20秒测速
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
> curl: (28) Operation timed out after 2000 milliseconds with 0 out of 0 bytes received
> 测速结果自己判断是否满意,如果不满意,再来一遍
> 请按任意键继续. . .
> 
> ===============================
> 优选的CF地址为 2807
> 3秒后对 2807 进行20秒测速
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - 吊销功能无法检查证书是否吊销。
> 测速结果自己判断是否满意,如果不满意,再来一遍
> 请按任意键继续. . .
> 

晚点我建个电报群沟通一下，你这个肯定是curl的问题

**Comment by huzy0909** [comment]
系统自带的curl运行正常，我也感觉是curl的问题。

**Comment by badafans** [comment]
> 系统自带的curl运行正常，我也感觉是curl的问题。

我刚创建了电报群，加入讨论 https://t.me/better_cloudflare_ip

**Comment by huzy0909** [comment]
问题已解决，根据官方最新说明就可以啦，谢谢 @badafans
