### ISSUE TITLE
无法使用IP优选工具

### ISSUE THREAD

**Issue by wuqingguo666** [badafans/better-cloudflare-ip#201]
![优选IP出现问题](https://github.com/user-attachments/assets/3a38db35-fe1c-49c8-ad9a-1994fefd0f5d)
![image](https://github.com/user-attachments/assets/15961677-f66c-4e3b-9ed7-c4dd24da90ab)

@badafans 版主您好，很感谢您的分享。我根据报错下载了完整的release版本，但还是出现这样的报错。不知道是哪里出了问题。期待您的解答。

**Comment by badafans** [comment]
你本地解压后，估计是被杀毒软件干掉了。请检查原始zip文件是否完整

**Comment by wuqingguo666** [comment]
> 你本地解压后，估计是被杀毒软件干掉了。请检查原始zip文件是否完整

感谢解答。果然是这样，我是在360压缩包里运行的，提示有风险，把杀毒软件关掉就行了。GitHub上分享的各种包和软件总是被各路杀毒软件误报，还真是挺麻烦。

**Comment by Bpc-CPU** [comment]
问题解决了是可以关掉issuse的吧？
