### ISSUE TITLE
更新后好像更难选到了

### ISSUE THREAD

**Issue by lyrielau** [badafans/better-cloudflare-ip#21]
更新后好像更难选到了，大部分都没速度了。是和测速服务器有吗？

**Comment by badafans** [comment]
> 更新后好像更难选到了，大部分都没速度了。是和测速服务器有吗？

https://t.me/better_cloudflare_ip   使用方面的问题反馈这里详细讨论

**Comment by emptysuns** [comment]
是更难选到了

---- 在 星期三, 11 十一月 2020 15:31:32 +0800 badafans <notifications@github.com> 撰写 ----




更新后好像更难选到了，大部分都没速度了。是和测速服务器有吗？


https://t.me/better_cloudflare_ip 使用方面的问题反馈这里详细讨论
