### ISSUE TITLE
安卓端无法安装

### ISSUE THREAD

**Issue by nixcry** [badafans/better-cloudflare-ip#22]
在Termux中粘贴安装指令并回车后，提示无此文件（预先已安装curl）。
Android版本：7.1.1

命令行记录------------------------------------------------
curl is already the newest version (7.73.0).
0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
$
$ ​curl https://proxy.freecdn.workers.dev/​?​url=https://raw.githubusercontent.com/badafans/better-cloudflare-ip/master/shell/cf.sh -o cf.sh ​&&​ chmod +x cf.sh ​&&​ ./cf.sh
**bash: ​curl https://proxy.freecdn.workers.dev/​?​url=https://raw.githubusercontent.com/badafans/better-cloudflare-ip/master/shell/cf.sh -o cf.sh ​: No such file or directory**
$

**Comment by badafans** [comment]
> 在Termux中粘贴安装指令并回车后，提示无此文件（预先已安装curl）。
> Android版本：7.1.1
> 
> 命令行记录------------------------------------------------
> curl is already the newest version (7.73.0).
> 0 upgraded, 0 newly installed, 0 to remove and 15 not upgraded.
> $
> $ ​curl [https://proxy.freecdn.workers.dev/​?​url=https://raw.githubusercontent.com/badafans/better-cloudflare-ip/master/shell/cf.sh -o cf.sh ​&&​ chmod +x cf.sh ​&&​ ./cf.sh](https://proxy.freecdn.workers.dev/%E2%80%8B?%E2%80%8Burl=https://raw.githubusercontent.com/badafans/better-cloudflare-ip/master/shell/cf.sh%C2%A0-o%C2%A0cf.sh%C2%A0%E2%80%8B&&%E2%80%8B%C2%A0chmod%C2%A0+x%C2%A0cf.sh%C2%A0%E2%80%8B&&%E2%80%8B%C2%A0./cf.sh)
> **bash: ​curl [https://proxy.freecdn.workers.dev/​?​url=https://raw.githubusercontent.com/badafans/better-cloudflare-ip/master/shell/cf.sh -o cf.sh ​](https://proxy.freecdn.workers.dev/%E2%80%8B?%E2%80%8Burl=https://raw.githubusercontent.com/badafans/better-cloudflare-ip/master/shell/cf.sh%C2%A0-o%C2%A0cf.sh%C2%A0%E2%80%8B): No such file or directory**
> $

上面链接的https地址不正确，你重新检查下是否是 https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/badafans/better-cloudflare-ip/master/shell/cf.sh

**Comment by nixcry** [comment]
已解决。
方法：不要复制粘贴，而是手动一个字一个字敲入命令行，执行成功。

结论：可能是文字编码差异导致Termux无法识别粘贴过来的某些字符，虽然肉眼看不出差别。

**Comment by nixcry** [comment]
Resolved by Author
