### ISSUE TITLE
请问可否添加iOS端的iSH版本

### ISSUE THREAD

**Issue by thisisnicoli** [badafans/better-cloudflare-ip#23]
iOS上的iSH和termux相似，是一个内建的terminal，建议添加。iSH通过apk命令管理安装，默认缺少很多软件，运行安卓版代码，需首先安装curl，并把最后的./cf.sh改为sh cf.sh，但经过修改之后，iSH无法执行declare，故实际表现出工不出力，没有真正进行延迟和速度测试，还望有空闲的话进一步适配:)

**Comment by badafans** [comment]
> iOS上的iSH和termux相似，是一个内建的terminal，建议添加。iSH通过apk命令管理安装，默认缺少很多软件，运行安卓版代码，需首先安装curl，并把最后的./cf.sh改为sh cf.sh，但经过修改之后，iSH无法执行declare，故实际表现出工不出力，没有真正进行延迟和速度测试，还望有空闲的话进一步适配:)

iOS设备目前没有测试环境，对于iOS用户不建议折腾这些
