### ISSUE TITLE
能否提供单个测试脚本，用来测试指定一批ip的速度情况？

### ISSUE THREAD

**Issue by leonsodey** [badafans/better-cloudflare-ip#26]
我已经通过优选IP找了一批IP，但这些IP会随着时间推移有的慢慢不能用，我把所有找到的IP放在（如BetterIP.txt文件中）。
能不能提供一个脚本，测试出 BetterIP.txt 文件中的所有IP的当前测速情况，并以  IP+空格+当前速率 保存到Result.txt文件中。
方便我判断，删选IP。
以上是一个思路，麻烦作者抽空看看研究一下。

**Comment by badafans** [comment]
> 我已经通过优选IP找了一批IP，但这些IP会随着时间推移有的慢慢不能用，我把所有找到的IP放在（如BetterIP.txt文件中）。
> 能不能提供一个脚本，测试出 BetterIP.txt 文件中的所有IP的当前测速情况，并以 IP+空格+当前速率 保存到Result.txt文件中。
> 方便我判断，删选IP。
> 以上是一个思路，麻烦作者抽空看看研究一下。

对于软件本身功能，做的比较简化。对于延申功能性开发，是交给用户自己去DIY适合自己使用的批处理文件，只需要略懂一些批处理逻辑即可完整开发修改自定义逻辑

**Comment by leonsodey** [comment]
> 对于软件本身功能，做的比较简化。对于延申功能性开发，是交给用户自己去DIY适合自己使用的批处理文件，只需要略懂一些批处理逻辑即可完整开发修改自定义逻辑

就是对批处理不是太懂所以才会有困惑，不过准备去大概了解下，也顺便提升一下自己。谢谢
