### ISSUE TITLE
希望支持直接在路由器中运行

### ISSUE THREAD

**Issue by zhanglianbo35** [badafans/better-cloudflare-ip#29]
梅林路由器没有bash，运行会报错。可否开发一个路由器版本的程序？

**Comment by badafans** [comment]
> 梅林路由器没有bash，运行会报错。可否开发一个路由器版本的程序？

之前考虑过，但是由于路由器系统各个程度的阉割不同路由器架构的原因，原版的shell命令里面有些命令运行无法通过，建议自己有条件的情况下在自己的路由器上测试修改

**Comment by zhanglianbo35** [comment]
我尝试改了。然而路由器没有bash的话 还是挺难改的

**Comment by sxml** [comment]
优选ip 没两天就变慢 
软路由半夜定时扫跑 再调用腾讯/阿里dns key 自动 修改ip 就完美

**Comment by zhucaidan** [comment]
> 优选ip 没两天就变慢
> 软路由半夜定时扫跑 再调用腾讯/阿里dns key 自动 修改ip 就完美

请问下openwrt可以跑吗？是不是直接按照linux的说明和代码去跑就好了？

**Comment by mysolen** [comment]
请问下楼主能否在openwrt上直接运行呢

**Comment by XIU2** [comment]
路由器 或 OpenWrt 可以试试我这个 Go 语言写的 Cloudflare CDN 测速工具：
- https://github.com/XIU2/CloudflareSpeedTest

优点是没有任何依赖，只有一个可执行文件，解压即用！

路由器 或 OpenWrt 下载时请选择 <kbd>ARM、ARM64、Mipsle</kbd> 其中之一，具体看路由器架构。
