### ISSUE TITLE
扫描结果不准确，不支持443端口

### ISSUE THREAD

**Issue by zhezhe168** [badafans/better-cloudflare-ip#31]
比如这个ip 35.200.109.86 ，实测速度很快，结果不在扫描结果中

**Comment by badafans** [comment]
> 35.200.109.86

35.200.109.86根本不是cloudflare的IP，是谷歌的IP，你这个IP很快很可能是别人拿来做转发的

**Comment by zhezhe168** [comment]
能否考虑支持非原生ip的扫描？

**Comment by badafans** [comment]
> 能否考虑支持非原生ip的扫描？

什么叫非原生IP？你都知道了非CF的IP了，再去扫描它有什么意义？
