### ISSUE TITLE
list out top 5 ips with highest throuput, would be very helpful.  

### ISSUE THREAD

**Issue by wangyubow** [badafans/better-cloudflare-ip#32]
If set target of 20Mbps, after several hours of tests, it may fail to select an IP to achieve 20Mbps.  In that case, list out the top 5 IPs with highest throuput would be very helpful.  
Otherwise, you have to define a reasonable target, try a few times. and is hard to obtain a good result.

If we have the function, simply define maximum target(if your local bandwidth is 100M, then set to 100M), then you will get top 5 ips within 1-2 hours. The results might be the best for us.

**Comment by badafans** [comment]
> If set target of 20Mbps, after several hours of tests, it may fail to select an IP to achieve 20Mbps. In that case, list out the top 5 IPs with highest throuput would be very helpful.
> Otherwise, you have to define a reasonable target, try a few times. and is hard to obtain a good result.
> 
> If we have the function, simply define maximum target(if your local bandwidth is 100M, then set to 100M), then you will get top 5 ips within 1-2 hours. The results might be the best for us.

我看你名字是中国人，我直接用中文回复你了。
首先，多个IP没有太大作用，对于某些修改host或者dns指向的时候，单个IP是最适合使用的
其次，随着路由的变化，建议自己加个while循环或者goto循环，做成定时执行脚本。
最后，我之所以搞得是shell和批处理的形式做发布，是因为后期预留了很多开放性的空间给个人做自定义功能
