### ISSUE TITLE
更新1208版本后无法测速

### ISSUE THREAD

**Issue by mavericklin** [badafans/better-cloudflare-ip#33]
生成随机IP 104.16.3.227206
生成随机IP 104.16.8.151203
生成随机IP 104.16.13.13225
生成随机IP 104.16.18.238225
生成随机IP 104.16.23.73169
生成随机IP 104.16.28.19019
生成随机IP 104.16.33.10124
生成随机IP 104.16.38.39161
生成随机IP 104.16.43.194151
生成随机IP 104.16.48.3543
生成随机IP 104.16.53.281
生成随机IP 104.16.58.20544
生成随机IP 104.16.63.48105
生成随机IP 104.16.68.22099
生成随机IP 104.16.73.239185
生成随机IP 104.16.78.2126
生成随机IP 104.16.83.1910
生成随机IP 104.16.88.51148
生成随机IP 104.16.93.148144
生成随机IP 104.16.98.143112
生成随机IP 104.16.103.48250
生成随机IP 104.16.108.574
生成随机IP 104.16.113.20498
生成随机IP 104.16.118.20460
生成随机IP 104.16.123.10118
生成随机IP 104.16.128.9819
生成随机IP 104.16.133.166166
生成随机IP 104.16.138.14463
生成随机IP 104.16.143.36204
生成随机IP 104.16.148.110101
生成随机IP 104.16.153.24132
生成随机IP 104.16.158.25421
生成随机IP 104.16.163.194182
生成随机IP 104.16.168.2667
生成随机IP 104.16.173.7528
生成随机IP 104.16.178.28219
生成随机IP 104.16.183.36128
生成随机IP 104.16.188.872
生成随机IP 104.16.193.237132
生成随机IP 104.16.198.19534
生成随机IP 104.16.203.164220
生成随机IP 104.16.208.203159
生成随机IP 104.16.213.20232
生成随机IP 104.16.218.9796
生成随机IP 104.16.223.82109
生成随机IP 104.16.228.252192
生成随机IP 104.16.233.1358
生成随机IP 104.16.238.21222
生成随机IP 104.16.243.1595
生成随机IP 104.16.248.19894
生成随机IP 104.16.253.58150
生成随机IP 104.17.2.87132
生成随机IP 104.17.7.040
生成随机IP 104.17.12.162222
生成随机IP 104.17.17.10155
生成随机IP 104.17.22.78208
生成随机IP 104.17.27.72159
生成随机IP 104.17.32.1054
生成随机IP 104.17.37.11190

贴上log.... 是不是随机算法生成范围有问题？

**Comment by yiguihai** [comment]
一样无法在termux使用，我去研究下

**Comment by badafans** [comment]
> 生成随机IP 104.16.3.227206
> 生成随机IP 104.16.8.151203
> 生成随机IP 104.16.13.13225
> 生成随机IP 104.16.18.238225
> 生成随机IP 104.16.23.73169
> 生成随机IP 104.16.28.19019
> 生成随机IP 104.16.33.10124
> 生成随机IP 104.16.38.39161
> 生成随机IP 104.16.43.194151
> 生成随机IP 104.16.48.3543
> 生成随机IP 104.16.53.281
> 生成随机IP 104.16.58.20544
> 生成随机IP 104.16.63.48105
> 生成随机IP 104.16.68.22099
> 生成随机IP 104.16.73.239185
> 生成随机IP 104.16.78.2126
> 生成随机IP 104.16.83.1910
> 生成随机IP 104.16.88.51148
> 生成随机IP 104.16.93.148144
> 生成随机IP 104.16.98.143112
> 生成随机IP 104.16.103.48250
> 生成随机IP 104.16.108.574
> 生成随机IP 104.16.113.20498
> 生成随机IP 104.16.118.20460
> 生成随机IP 104.16.123.10118
> 生成随机IP 104.16.128.9819
> 生成随机IP 104.16.133.166166
> 生成随机IP 104.16.138.14463
> 生成随机IP 104.16.143.36204
> 生成随机IP 104.16.148.110101
> 生成随机IP 104.16.153.24132
> 生成随机IP 104.16.158.25421
> 生成随机IP 104.16.163.194182
> 生成随机IP 104.16.168.2667
> 生成随机IP 104.16.173.7528
> 生成随机IP 104.16.178.28219
> 生成随机IP 104.16.183.36128
> 生成随机IP 104.16.188.872
> 生成随机IP 104.16.193.237132
> 生成随机IP 104.16.198.19534
> 生成随机IP 104.16.203.164220
> 生成随机IP 104.16.208.203159
> 生成随机IP 104.16.213.20232
> 生成随机IP 104.16.218.9796
> 生成随机IP 104.16.223.82109
> 生成随机IP 104.16.228.252192
> 生成随机IP 104.16.233.1358
> 生成随机IP 104.16.238.21222
> 生成随机IP 104.16.243.1595
> 生成随机IP 104.16.248.19894
> 生成随机IP 104.16.253.58150
> 生成随机IP 104.17.2.87132
> 生成随机IP 104.17.7.040
> 生成随机IP 104.17.12.162222
> 生成随机IP 104.17.17.10155
> 生成随机IP 104.17.22.78208
> 生成随机IP 104.17.27.72159
> 生成随机IP 104.17.32.1054
> 生成随机IP 104.17.37.11190
> 
> 贴上log.... 是不是随机算法生成范围有问题？

执行 rm -rf data.txt   再运行命令即可，旧的data.txt没有删除造成的

**Comment by badafans** [comment]
> 一样无法在termux使用，我去研究下

执行 rm -rf data.txt 再运行命令即可，旧的data.txt没有删除造成的

**Comment by yiguihai** [comment]
> > 一样无法在termux使用，我去研究下
> 
> 执行 rm -rf data.txt 再运行命令即可，旧的data.txt没有删除造成的

可以了

**Comment by mavericklin** [comment]
great thanks
