### ISSUE TITLE
请问可否在openwrt下运行呢？

### ISSUE THREAD

**Issue by zhucaidan** [badafans/better-cloudflare-ip#34]
请问可否在openwrt下运行呢？
是否可以生成一个类似better-cloudflare-ip-luci-app.ipk之类的插件包

**Comment by badafans** [comment]
> 请问可否在openwrt下运行呢？
> 是否可以生成一个类似better-cloudflare-ip-luci-app.ipk之类的插件包

支持openwrt运行的shell版本，这两天将会更新发布

**Comment by ulpyuxa** [comment]
期待openwrt的shell版本，太需要这个了。

**Comment by jdwchiao** [comment]
> > 请问可否在openwrt下运行呢？
> > 是否可以生成一个类似better-cloudflare-ip-luci-app.ipk之类的插件包
> 
> 支持openwrt运行的shell版本，这两天将会更新发布

你好openwrt运行的shell版出来了吗在哪里呢

**Comment by XIU2** [comment]
路由器 或 OpenWrt 可以试试我这个 Go 语言写的 Cloudflare CDN 测速工具：
- https://github.com/XIU2/CloudflareSpeedTest

优点是没有任何依赖，只有一个可执行文件，解压即用！

路由器 或 OpenWrt 下载时请选择 <kbd>ARM、ARM64、Mipsle</kbd> 三个版本其中之一，具体看路由器架构。

**Comment by zhucaidan** [comment]
> 路由器 或 OpenWrt 可以试试我这个 Go 语言写的 Cloudflare CDN 测速工具：
> 
> * https://github.com/XIU2/CloudflareSpeedTest
> 
> 优点是没有任何依赖，只有一个可执行文件，解压即用！
> 
> 路由器 或 OpenWrt 下载时请选择 ARM、ARM64、Mipsle 三个版本其中之一，具体看路由器架构。

好的，我去试试，先star了

**Comment by badafans** [comment]
最新版本已经支持OP
