### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by Jacobax** [badafans/better-cloudflare-ip#36]
win10 20H2
显示方块
运行_CF优选IP.bat_跑两圈后出现，运行_Colo提取.bat_也出现，图为运行_Colo提取.bat_结果
![1](https://user-images.githubusercontent.com/23228895/101544342-7bf45600-39e0-11eb-9a6b-7b5af8328286.png)

**Comment by badafans** [comment]
> win10 20H2
> 显示方块
> 运行_CF优选IP.bat_跑两圈后出现，运行_Colo提取.bat_也出现，图为运行_Colo提取.bat_结果
> ![1](https://user-images.githubusercontent.com/23228895/101544342-7bf45600-39e0-11eb-9a6b-7b5af8328286.png)

Windows部分版本执行批处理for循环之后会出现编码乱码问题，这个问题没有系统环境做统一测试，不过这个是不影响程序运行的结果的。

**Comment by cgworld2019** [comment]
无限死循环，每次到等待10秒优选3个之后，又跳回刚启动状态。完全是无用功。能否提供一个次新版下载？

**Comment by badafans** [comment]
> 无限死循环，每次到等待10秒优选3个之后，又跳回刚启动状态。完全是无用功。能否提供一个次新版下载？

加入 https://t.me/better_cloudflare_ip 获取支持

**Comment by cgworld2019** [comment]
> > 无限死循环，每次到等待10秒优选3个之后，又跳回刚启动状态。完全是无用功。能否提供一个次新版下载？
> 
> 加入 https://t.me/better_cloudflare_ip 获取支持

已经解决，谢谢，加油！
