### ISSUE TITLE
20201208 更新后 cf.sh 中未修改版本号

### ISSUE THREAD

**Issue by leemars** [badafans/better-cloudflare-ip#37]
会导致 cf.sh 一直认为需要更新，无法继续运行。

**Comment by badafans** [comment]
> 会导致 cf.sh 一直认为需要更新，无法继续运行。

就是为了让你去更新，下载github发布的最新版使用

**Comment by leemars** [comment]
扶额……找到原因了，是我本地环境里面用的是之前遗留下来的 fping-4.2 目录里面的 cf.sh，难怪没有更新。误报了误报了。
