### ISSUE TITLE
Ma执行shell脚本死循环

### ISSUE THREAD

**Issue by Cregin** [badafans/better-cloudflare-ip#38]
sed: 1: "3~5p;4~5p": invalid command code ~
sed: 1: "{N;s/\n/\t/p}": bad flag in substitute command: '}'
选取30个丢包率最少的IP地址下载测速
等待测速进程结束,筛选出三个优选的IP

然后又开始

正在测试 ICMP 丢包率:进程数 39,已完成 8 %

。。。。。。

**Comment by lzyroot** [comment]
`sed: 1: "3~5p;4~5p": invalid command code ~
sed: 1: "{N;s/\n/\t/p}": bad flag in substitute command: '}'
选取30个丢包率最少的IP地址下载测速
等待测速进程结束,筛选出三个优选的IP`

**Comment by badafans** [comment]
> sed: 1: "3~5p;4~5p": invalid command code ~
> sed: 1: "{N;s/\n/\t/p}": bad flag in substitute command: '}'
> 选取30个丢包率最少的IP地址下载测速
> 等待测速进程结束,筛选出三个优选的IP
> 
> 然后又开始
> 
> 正在测试 ICMP 丢包率:进程数 39,已完成 8 %
> 
> 。。。。。。

这个问题，部分系统内置的sed命令调用的参数不一样

**Comment by badafans** [comment]
请使用最新版本，已经支持mac
