### ISSUE TITLE
windows10系统下卡在测速倒数环节，倒数完直接重新循环脚本，不进入测速环节。

### ISSUE THREAD

**Issue by eat-peach** [badafans/better-cloudflare-ip#40]
RT

**Comment by badafans** [comment]
你看下本地的temp文件夹是否生成超过3个文件

**Comment by nickochen** [comment]
我也遇到同样的问题

**Comment by lqrqw13** [comment]
我也遇到同样的问题，本地的temp文件夹是为空，没有文件

**Comment by lqrqw13** [comment]
解决了，用notepad++在右下角，把unix右键改win就可以了

**Comment by Roufoye** [comment]
用了最新版本0308，也有这个问题，ping之后temp文件夹为空，提示找不到文件然后重新开始ping一直这样循环

**Comment by Roufoye** [comment]
楼上说的解决方案无效

**Comment by Tylxer** [comment]
> 楼上说的解决方案无效

先将better-cloudflare-ip放到C盘根目录，打开双击自解压curl.exe，将目录里的所有exe全部设为以管理员运行。然后以管理员启动bat
