### ISSUE TITLE
20201208 win版本 下载后报病毒

### ISSUE THREAD

**Issue by Se7enMuting** [badafans/better-cloudflare-ip#44]
win10自带的安全中心报病毒
![image](https://user-images.githubusercontent.com/889925/103155127-ae22f780-47d7-11eb-998c-45586ff4a6ca.png)

**Comment by badafans** [comment]
截图不全，不到你文件后缀名

**Comment by onlyJinx** [comment]
同款, 我这里在chrome这里就被干掉了
![image](https://user-images.githubusercontent.com/21324835/103166442-06500d00-485d-11eb-9e39-79e68614cac1.png)

**Comment by badafans** [comment]
> 同款, 我这里在chrome这里就被干掉了
> ![image](https://user-images.githubusercontent.com/21324835/103166442-06500d00-485d-11eb-9e39-79e68614cac1.png)

这个我就没法控制了，你可以对比hash值，跟早期的文件一样的

**Comment by onlyJinx** [comment]
哈哈, 那有没有其他建议呢, 我用ie/edge/chrome都是被杀了

**Comment by badafans** [comment]
> 哈哈, 那有没有其他建议呢, 我用ie/edge/chrome都是被杀了

应该是zip文件被国内大厂标记病毒了，等下个版本上传后更新hash就好了

**Comment by onlyJinx** [comment]
OK, thanks.
