### ISSUE TITLE
什么时候考虑支持 IPv6 地址池

### ISSUE THREAD

**Issue by zhangjint5** [badafans/better-cloudflare-ip#48]
什么时候考虑支持 Cloudflare 的 IPv6 地址池

**Comment by badafans** [comment]
1.ipv6数量繁多不好管理
2.国际宽带ipv6的流量占比跟ipv4相比还是有一定差距
3.ipv6路由线路容易出现节点乱跳的问题

**Comment by zhangjint5** [comment]
IPv4 要被玩坏了！~~~~~ :)

**Comment by badafans** [comment]
新版本已经完美支持IPV6
