### ISSUE TITLE
Docker 容器内测试无法显示完整结果

### ISSUE THREAD

**Issue by LunaticTian** [badafans/better-cloudflare-ip#5]
运行时的输出与ubuntu中输出相同，但是最后出现运行结果只显示：满足 100 Mbps带宽需求,峰值速度 kB/s,总计用时 110 秒。
且测试三次结果都相同，用时相同。

群晖:docker
镜像:python3.6
已正常编译fping-4.2

修改脚本，删除clear输出显示。
error: 
./cf.sh: line 5745: 12.5: syntax error: invalid arithmetic operator (error token is ".5")
./cf.sh: line 5746: /1024: syntax error: operand expected (error token is "/1024")

**Comment by dawenhaozx** [comment]
M=`printf "%.0f\n" $i`

**Comment by badafans** [comment]
> 运行时的输出与ubuntu中输出相同，但是最后出现运行结果只显示：满足 100 Mbps带宽需求,峰值速度 kB/s,总计用时 110 秒。
> 且测试三次结果都相同，用时相同。
> 
> 群晖:docker
> 镜像:python3.6
> 已正常编译fping-4.2
> 
> 修改脚本，删除clear输出显示。
> error:
> ./cf.sh: line 5745: 12.5: syntax error: invalid arithmetic operator (error token is ".5")
> ./cf.sh: line 5746: /1024: syntax error: operand expected (error token is "/1024")

最新版的已经修复小数位计算的问题，请更新
