### ISSUE TITLE
电信宽带 越来越难选出优选IP了

### ISSUE THREAD

**Issue by zikywang** [badafans/better-cloudflare-ip#50]
请问一下 是因为电信对CF的ip进行了限制么？

**Comment by kevinliu2046** [comment]
同电信，找到最快的IP从来不会超过2M

**Comment by badafans** [comment]
情况反馈 https://t.me/better_cloudflare_ip

**Comment by holywd** [comment]
电信也要分地方的，沿海地区的速度普遍高于内陆，我这电信高峰期有150Mbps

**Comment by Comah** [comment]
深圳移动3分钟不到就可以优选出300M的
