### ISSUE TITLE
Mac下卡在等待ICMP进程结束

### ISSUE THREAD

**Issue by loofahsf** [badafans/better-cloudflare-ip#53]
系统：osx 10.15.6
文件：shell/cf.sh
64行：p=$(ps -ef | grep ping | grep -v "grep" | wc -l)
因为运行的其它进程信息中存在 --globalTypingsCacheLocation 这样的文字，导致了匹配出错；
本地临时修改成了：p=$(ps -ef | grep ping\s+ | grep -v "grep" | wc -l)
后续大佬有时间可以优化一波~

**Comment by badafans** [comment]
我没有mac测试环境，基本也没有考虑苹果全家桶

**Comment by loofahsf** [comment]
好的，感谢大佬提供的工具
