### ISSUE TITLE
[讨论]提个方向，如何把cloudflare host的域名都解析到固定的几个IP上去？ 

### ISSUE THREAD

**Issue by zz5678** [badafans/better-cloudflare-ip#56]
在这里提了同样的问题，看看谁有兴趣和解决方案
https://github.com/felixonmars/dnsmasq-china-list/issues/345

**Comment by Elypha** [comment]
一个比较原始的方法：v2ray可以在出站的时候redirect，配合routing
不过个人感觉实践意义不大_(:з」∠)_

**Comment by aa65535** [comment]
不要想着找到所有使用 Cloudflare 的网站域名， Cloudflare 有公开的 IP 段，所以 DNS 解析结果在这个 IP 段内的就是使用了 Cloudflare 的网站，写个 DNS 工具将 DNS 的响应包修改成优选 IP 就行了。

工具在此： https://github.com/aa65535/CloudflareDNS
需要自己编译。
