### ISSUE TITLE
用修改过的fping 4.2,Ubuntu 20.10编译会有错误

### ISSUE THREAD

**Issue by strategist922** [badafans/better-cloudflare-ip#57]
下载最新的版的linux src (fping 4.2修改版)编译会有下列问题:
PS. 编译最新的fping 5.0则可以正常编译完成
gcc version 10.2.0 (Ubuntu 10.2.0-13ubuntu1)

Error如下:
k’ output between 4 and 11 bytes into a destination of size 10
   38 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   39 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fping.c:2595:26: warning: ‘%02d’ directive writing 2 bytes into a region of size between 1 and 8 [-Wformat-overflow=]
 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
      |                          ^~~~
fping.c:2595:22: note: directive argument in the range [0, 99]
 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
      |                      ^~~~~~~~~
In file included from /usr/include/stdio.h:866,
                 from fping.c:44:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:38:10: note: ‘__builtin___sprintf_chk’ output between 5 and 12 bytes into a destination of size 10
   38 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   39 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fping.c: In function ‘add_name’:
fping.c:2340:82: warning: ‘)’ directive output may be truncated writing 1 byte into a region of size between 0 and 510 [-Wformat-truncation=]
 2340 | ntf(nameaddrbuf, sizeof(nameaddrbuf) / sizeof(char), "%s (%s)", printname, addrbuf);
      |                                                             ^

In file included from /usr/include/stdio.h:866,
                 from fping.c:44:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:70:10: note: ‘__builtin___snprintf_chk’ output between 4 and 514 bytes into a destination of size 512
   70 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   71 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/fping-fping.Tpo .deps/fping-fping.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-seqmap.o -MD -MP -MF .deps/fping-seqmap.Tpo -c -o fping-seqmap.o `test -f 'seqmap.c' || echo './'`seqmap.c
mv -f .deps/fping-seqmap.Tpo .deps/fping-seqmap.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket4.o -MD -MP -MF .deps/fping-socket4.Tpo -c -o fping-socket4.o `test -f 'socket4.c' || echo './'`socket4.c
mv -f .deps/fping-socket4.Tpo .deps/fping-socket4.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-optparse.o -MD -MP -MF .deps/fping-optparse.Tpo -c -o fping-optparse.o `test -f 'optparse.c' || echo './'`optparse.c
mv -f .deps/fping-optparse.Tpo .deps/fping-optparse.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket6.o -MD -MP -MF .deps/fping-socket6.Tpo -c -o fping-socket6.o `test -f 'socket6.c' || echo './'`socket6.c
mv -f .deps/fping-socket6.Tpo .deps/fping-socket6.Po
gcc -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2   -o fping fping-fping.o fping-seqmap.o fping-socket4.o fping-optparse.o fping-socket6.o
/usr/bin/ld: fping-socket4.o:/home/NetPerf/linux/src/fping.h:14: multiple definition of `random_data_flag'; fping-fping.o:/home/NetPerf/linux/src/fping.h:14: first defined here
/usr/bin/ld: fping-socket6.o:/home/NetPerf/linux/src/fping.h:14: multiple definition of `random_data_flag'; fping-fping.o:/home/NetPerf/linux/src/fping.h:14: first defined here
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:350: fping] Error 1

**Comment by Noo13-man** [comment]
#13 
你可以试一试
