### ISSUE TITLE
Worker次数炸了 已在我的分支修复

### ISSUE THREAD

**Issue by BlueSkyXN** [badafans/better-cloudflare-ip#58]
导致无法测速QAQ 这个里面存了啥 就只有data.txt和temp.txt吗，有源码吗

**Comment by KyonCN** [comment]
免费的套餐好像是一天十万次吧

**Comment by BlueSkyXN** [comment]
修复了workers爆炸的问题，转移资源到pages

https://www.blueskyxn.com/202102/4217.html

**Comment by badafans** [comment]
> 修复了workers爆炸的问题，转移资源到pages
> 
> https://www.blueskyxn.com/202102/4217.html

我这个workers上后台是由服务的，不光是资源缓存问题。需要用到workers的代码进行计算。2021年2月25日下午5点到5点42分之间，我的workers服务受到了不明来源的攻击，请求次数13.9万次。超出了免费的10万次限制，导致服务停止了几个小时。

**Comment by liuhongzhe111** [comment]
我还以为是升级windows10 21H1导致的不能单IP测速，原来这么多人和我一样。
