### ISSUE TITLE
Worker炸了

### ISSUE THREAD

**Issue by flower-elf** [badafans/better-cloudflare-ip#60]
导致无法测速（刚才一看429了），我看昨天有人也反馈了这个问题。。。
建议搞多两个账号来放置资源吧，要不然挂了测不了速度很难受

**Comment by badafans** [comment]
后面打算迁移服务了，workers被别人攻击了

**Comment by BlueSkyXN** [comment]
> 导致无法测速（刚才一看429了），我看昨天有人也反馈了这个问题。。。
> 建议搞多两个账号来放置资源吧，要不然挂了测不了速度很难受

https://github.com/badafans/better-cloudflare-ip/issues/58

**Comment by raindrops2005** [comment]
> 
> 
> > 导致无法测速（刚才一看429了），我看昨天有人也反馈了这个问题。。。
> > 建议搞多两个账号来放置资源吧，要不然挂了测不了速度很难受
> 
> #58

已经看到了

**Comment by sw586** [comment]
扫描不了了

**Comment by badafans** [comment]
已经发布新的版本，抛开了CF Workers托管，让恶意攻击我Workers的人歇歇吧

**Comment by raindrops2005** [comment]
> 已经发布新的版本，抛开了CF Workers托管，让恶意攻击我Workers的人歇歇吧

目前新版本可正常使用了

**Comment by liuhongzhe111** [comment]
新版本可以单IP测速了，但是一直循环筛选不出IP，郁闷。

**Comment by lixiang810** [comment]
> 已经发布新的版本，抛开了CF Workers托管，让恶意攻击我Workers的人歇歇吧

简单说一下结论吧。你这个脚本应该是动到了一些机场主的蛋糕。机场这个圈子很混乱，互相DD/CC基本是常态。
任何免费项目做大了、做出名了，都会动到收费者的利益，然后被收费的人群起攻之，希望repo主能有这个思想觉悟。我向你们致敬。

**Comment by raindrops2005** [comment]
> 
> 
> > 已经发布新的版本，抛开了CF Workers托管，让恶意攻击我Workers的人歇歇吧
> 
> 简单说一下结论吧。你这个脚本应该是动到了一些机场主的蛋糕。机场这个圈子很混乱，互相DD/CC基本是常态。
> 任何免费项目做大了、做出名了，都会动到收费者的利益，然后被收费的人群起攻之，希望repo主能有这个思想觉悟。我向你们致敬。

这种情况没办法避免的。总有一些小肚鸡肠的人在那里搞事，也不一定是机场主。也有可能是一些别有用心的人，但是开源项目怎么搞都搞不死的，这个不需要担心。

**Comment by Andy-Leo** [comment]
攻击你的人是不是死盯上你了啊，如果它们的攻击方式是DOS你的Worker，我提议你把Worker配置项暴出来让我们填自己的Worker

**Comment by dzcpy** [comment]
默默的问下，有办法能不通过后台的这个服务，直接获取到所有cloudflare的可用ip吗？这个数据是从哪里获取出来的？

**Comment by lixiang810** [comment]
> 默默的问下，有办法能不通过后台的这个服务，直接获取到所有cloudflare的可用ip吗？这个数据是从哪里获取出来的？

可以，cf官网有它的ip段，但不是全通，要自己拿服务器ping来测试

**Comment by dzcpy** [comment]
> > 默默的问下，有办法能不通过后台的这个服务，直接获取到所有cloudflare的可用ip吗？这个数据是从哪里获取出来的？
> 
> 可以，cf官网有它的ip段，但不是全通，要自己拿服务器ping来测试

也是个办法，不过我看 https://service.udpfile.com/ 给出的 ip 也有不在这个 ip 段里的，不知道是怎么获取的

**Comment by dzcpy** [comment]
https://service.udpfile.com/ 又挂了，有没有其他的替代选项或者自建服务器方案？

**Comment by dzcpy** [comment]
貌似 cf 的 ip 都被墙了？
