### ISSUE TITLE
今天大佬放出来的新版，如果想刷两个优选IP就很难刷出来了……

### ISSUE THREAD

**Issue by pprice2018** [badafans/better-cloudflare-ip#66]
由于设备的需求，需要刷两个优选IP，今天的新本版，在刷完第一个IP之后，第二次运行优选程序，还是会刷出来第一个IP。而且发现对上一个版本也不能用了，刷完IP延时就提示有新版要更新……

**Comment by badafans** [comment]
这个是数据库学习的过程，你如果设置的速度要求比较低，你这个IP大概率的每次都能选中。建议设置一个较大的速度值让数据库学习一段时间，让你的节点数据库自动填充到一定程度后数据级别就更加精确了

**Comment by pprice2018** [comment]
提高了速度值确实有效，之前为了高命中，设置了30mbps，提高到七八十之后，虽然第一个出来还是那个IP，但不满足条件之后会自动跑第二个，自己手动复制一下就好了。
不知道像电信这种每日换自动强制换IP的环境，对数据库自我学习有没有不好的影响。

**Comment by badafans** [comment]
数据学习，是增对你的运营商自治域以及城市信息划分的，你的IP变动没有影响。另外这个是共享数据模式，你学习的同时和你同一个城市同一个运营商自治域的用户也在和你一起提供数据库学习的数据。相互进化升级的过程
