### ISSUE TITLE
iOS 使用ish会闪退

### ISSUE THREAD

**Issue by taishunanpo** [badafans/better-cloudflare-ip#68]
请问大佬有办法解决吗？apk update      Apk add curl   curl https://proxy.freecdn.workers.dev/?url=https://raw.githubusercontent.com/badafans/better-cloudflare-ip/master/shell/cf.sh -o cf.sh && chmod +x cf.sh && ./cf.sh

**Comment by KimiBear** [comment]
我的也一样，闪退，希望大神检查一下原因

**Comment by badafans** [comment]
近期会考虑开发ish兼容的脚本

**Comment by KimiBear** [comment]
> 近期会考虑开发ish兼容的脚本

ISH兼容脚本出来了吗？等了好久！ @badafans

**Comment by badafans** [comment]
ios用户可以试下最新版本用ashell跑，测试进程不要开太多
