### ISSUE TITLE
强烈要求不要封杀老版本

### ISSUE THREAD

**Issue by somebird** [badafans/better-cloudflare-ip#69]
在同等条件下，新版本找了半个小时一个合格的IP都筛不出来。老版本几分钟就筛出来了，强烈要求不要封杀老版本

**Comment by Chuang2016** [comment]
支持不要封杀老版本，新版本太慢了，希望大佬放开版本权限呀，新老版本都可以使用呀

**Comment by zhumao520** [comment]
多跑跑看 会出奇迹的

**Comment by badafans** [comment]
问题反馈  [https://t.me/better_cloudflare_ip](url)

**Comment by muziling** [comment]
我也是这问题， 跑几个小时都找不到符合的地址， 有没有自己搭建测速文件服务器的教程  ，即 https://speed.haoren.ml/cache.jpg 这个文件的搭建教程

**Comment by badafans** [comment]
> 我也是这问题， 跑几个小时都找不到符合的地址， 有没有自己搭建测速文件服务器的教程 ，即 https://speed.haoren.ml/cache.jpg 这个文件的搭建教程， 不知道是不是这个地址太多人在测速，导致总带宽不够

这个域名到期了  已经无法继续使用

**Comment by muziling** [comment]
> > 我也是这问题， 跑几个小时都找不到符合的地址， 有没有自己搭建测速文件服务器的教程 ，即 https://speed.haoren.ml/cache.jpg 这个文件的搭建教程， 不知道是不是这个地址太多人在测速，导致总带宽不够
> 
> 这个域名到期了 已经无法继续使用

有自建这个地址的教程吗？

**Comment by badafans** [comment]
> > > 我也是这问题， 跑几个小时都找不到符合的地址， 有没有自己搭建测速文件服务器的教程 ，即 https://speed.haoren.ml/cache.jpg 这个文件的搭建教程， 不知道是不是这个地址太多人在测速，导致总带宽不够
> > 
> > 
> > 这个域名到期了 已经无法继续使用
> 
> 有自建这个地址的教程吗？

随便找个图片就可以被cdn缓存了

**Comment by BlueSkyXN** [comment]
> 在同等条件下，新版本找了半个小时一个合格的IP都筛不出来。老版本几分钟就筛出来了，强烈要求不要封杀老版本

https://github.com/BlueSkyXN/CFIP
我在维护老版本算法，可以试试 @somebird @Chuang2016 @muziling

**Comment by badafans** [comment]
封杀老版本是为了更好的统一维护，没有历史包袱
