### ISSUE TITLE
fping 编译错误

### ISSUE THREAD

**Issue by BruceZhang1993** [badafans/better-cloudflare-ip#7]
> fping-4.2 · (master) ★  ⟩ ./configure                                                         /t/b/fping-4.2
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking for netinet/icmp6.h... yes
> checking whether SO_TIMESTAMP is declared... yes
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> /bin/sh: /home/bruce/missing: No such file or directory
> configure: WARNING: 'missing' script is too old or missing
> checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking for style of include used by make... GNU
> checking whether make supports nested variables... yes
> checking dependency style of gcc... gcc3
> checking whether to enable maintainer-specific portions of Makefiles... no
> checking for gcc... (cached) gcc
> checking whether we are using the GNU C compiler... (cached) yes
> checking whether gcc accepts -g... (cached) yes
> checking for gcc option to accept ISO C89... (cached) none needed
> checking whether gcc understands -c and -o together... (cached) yes
> checking for gcc option to accept ISO C99... none needed
> checking for gcc option to accept ISO Standard C... (cached) none needed
> checking how to run the C preprocessor... gcc -E
> checking for gethostbyname... yes
> checking for connect... yes
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for unistd.h... (cached) yes
> checking sys/file.h usability... yes
> checking sys/file.h presence... yes
> checking for sys/file.h... yes
> checking for stdlib.h... (cached) yes
> checking sys/select.h usability... yes
> checking sys/select.h presence... yes
> checking for sys/select.h... yes
> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating doc/Makefile
> config.status: creating src/Makefile
> config.status: creating config.h
> config.status: executing depfiles commands
> 
> fping-4.2 · (master) ★  ⟩ make                                                                /t/b/fping-4.2
> make  all-recursive
> make[1]: 进入目录“/tmp/better-cloudflare-ip/fping-4.2”
> Making all in doc
> make[2]: 进入目录“/tmp/better-cloudflare-ip/fping-4.2/doc”
> make[2]: 对“all”无需做任何事。
> make[2]: 离开目录“/tmp/better-cloudflare-ip/fping-4.2/doc”
> Making all in src
> make[2]: 进入目录“/tmp/better-cloudflare-ip/fping-4.2/src”
> gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-fping.o -MD -MP -MF .deps/fping-fping.Tpo -c -o fping-fping.o `test -f 'fping.c' || echo './'`fping.c
> fping.c: 在函数‘sprint_tm’中:
> fping.c:2599:28: 警告：‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
>  2599 |         sprintf(buf, "%d.%d", t / 100, (t % 100) / 10);
>       |                            ^
> fping.c:2599:9: 附注：‘sprintf’ output between 4 and 11 bytes into a destination of size 10
>  2599 |         sprintf(buf, "%d.%d", t / 100, (t % 100) / 10);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> fping.c:2595:26: 警告：‘%02d’ directive writing 2 bytes into a region of size between 1 and 8 [-Wformat-overflow=]
>  2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
>       |                          ^~~~
> fping.c:2595:22: 附注：directive argument in the range [0, 99]
>  2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
>       |                      ^~~~~~~~~
> fping.c:2595:9: 附注：‘sprintf’ output between 5 and 12 bytes into a destination of size 10
>  2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
>       |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> fping.c: 在函数‘add_name’中:
> fping.c:2340:82: 警告：‘)’ directive output may be truncated writing 1 byte into a region of size between 0 and 510 [-Wformat-truncation=]
>  2340 |                 snprintf(nameaddrbuf, sizeof(nameaddrbuf) / sizeof(char), "%s (%s)", printname, addrbuf);
>       |                                                                                  ^
> fping.c:2340:17: 附注：‘snprintf’ output between 4 and 514 bytes into a destination of size 512
>  2340 |                 snprintf(nameaddrbuf, sizeof(nameaddrbuf) / sizeof(char), "%s (%s)", printname, addrbuf);
>       |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> mv -f .deps/fping-fping.Tpo .deps/fping-fping.Po
> gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-seqmap.o -MD -MP -MF .deps/fping-seqmap.Tpo -c -o fping-seqmap.o `test -f 'seqmap.c' || echo './'`seqmap.c
> mv -f .deps/fping-seqmap.Tpo .deps/fping-seqmap.Po
> gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket4.o -MD -MP -MF .deps/fping-socket4.Tpo -c -o fping-socket4.o `test -f 'socket4.c' || echo './'`socket4.c
> mv -f .deps/fping-socket4.Tpo .deps/fping-socket4.Po
> gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-optparse.o -MD -MP -MF .deps/fping-optparse.Tpo -c -o fping-optparse.o `test -f 'optparse.c' || echo './'`optparse.c
> mv -f .deps/fping-optparse.Tpo .deps/fping-optparse.Po
> gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket6.o -MD -MP -MF .deps/fping-socket6.Tpo -c -o fping-socket6.o `test -f 'socket6.c' || echo './'`socket6.c
> mv -f .deps/fping-socket6.Tpo .deps/fping-socket6.Po
> gcc -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2   -o fping fping-fping.o fping-seqmap.o fping-socket4.o fping-optparse.o fping-socket6.o  
> /usr/bin/ld: fping-socket4.o:/tmp/better-cloudflare-ip/fping-4.2/src/fping.h:14: multiple definition of `random_data_flag'; fping-fping.o:/tmp/better-cloudflare-ip/fping-4.2/src/fping.h:14: first defined here
> /usr/bin/ld: fping-socket6.o:/tmp/better-cloudflare-ip/fping-4.2/src/fping.h:14: multiple definition of `random_data_flag'; fping-fping.o:/tmp/better-cloudflare-ip/fping-4.2/src/fping.h:14: first defined here
> collect2: 错误：ld 返回 1
> make[2]: *** [Makefile:350：fping] 错误 1
> make[2]: 离开目录“/tmp/better-cloudflare-ip/fping-4.2/src”
> make[1]: *** [Makefile:358：all-recursive] 错误 1
> make[1]: 离开目录“/tmp/better-cloudflare-ip/fping-4.2”
> make: *** [Makefile:298：all] 错误 2
> 
> fping-4.2 · (master) ★  ⟩ ld --version                                                      /t/b/fping-4.2 2
> GNU ld (GNU Binutils) 2.35
> Copyright (C) 2020 Free Software Foundation, Inc.
> 这个程序是自由软件；您可以遵循GNU 通用公共授权版本 3 或
> (您自行选择的) 稍后版本以再次散布它。
> 这个程序完全没有任何担保。
> 
> fping-4.2 · (master) ★  ⟩ gcc --version                                                       /t/b/fping-4.2
> gcc (GCC) 10.2.0
> Copyright © 2020 Free Software Foundation, Inc.
> 本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
> 包括没有适销性和某一专用目的下的适用性担保。

gcc: 10.2.0
ld: 2.35

**Comment by badafans** [comment]
> > fping-4.2 · (master) ★  ⟩ ./configure                                                         /t/b/fping-4.2
> > checking for gcc... gcc
> > checking whether the C compiler works... yes
> > checking for C compiler default output file name... a.out
> > checking for suffix of executables...
> > checking whether we are cross compiling... no
> > checking for suffix of object files... o
> > checking whether we are using the GNU C compiler... yes
> > checking whether gcc accepts -g... yes
> > checking for gcc option to accept ISO C89... none needed
> > checking whether gcc understands -c and -o together... yes
> > checking for netinet/icmp6.h... yes
> > checking whether SO_TIMESTAMP is declared... yes
> > checking build system type... x86_64-unknown-linux-gnu
> > checking host system type... x86_64-unknown-linux-gnu
> > checking target system type... x86_64-unknown-linux-gnu
> > checking for a BSD-compatible install... /usr/bin/install -c
> > checking whether build environment is sane... yes
> > /bin/sh: /home/bruce/missing: No such file or directory
> > configure: WARNING: 'missing' script is too old or missing
> > checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> > checking for gawk... gawk
> > checking whether make sets $(MAKE)... yes
> > checking for style of include used by make... GNU
> > checking whether make supports nested variables... yes
> > checking dependency style of gcc... gcc3
> > checking whether to enable maintainer-specific portions of Makefiles... no
> > checking for gcc... (cached) gcc
> > checking whether we are using the GNU C compiler... (cached) yes
> > checking whether gcc accepts -g... (cached) yes
> > checking for gcc option to accept ISO C89... (cached) none needed
> > checking whether gcc understands -c and -o together... (cached) yes
> > checking for gcc option to accept ISO C99... none needed
> > checking for gcc option to accept ISO Standard C... (cached) none needed
> > checking how to run the C preprocessor... gcc -E
> > checking for gethostbyname... yes
> > checking for connect... yes
> > checking for grep that handles long lines and -e... /usr/bin/grep
> > checking for egrep... /usr/bin/grep -E
> > checking for ANSI C header files... yes
> > checking for sys/types.h... yes
> > checking for sys/stat.h... yes
> > checking for stdlib.h... yes
> > checking for string.h... yes
> > checking for memory.h... yes
> > checking for strings.h... yes
> > checking for inttypes.h... yes
> > checking for stdint.h... yes
> > checking for unistd.h... yes
> > checking for unistd.h... (cached) yes
> > checking sys/file.h usability... yes
> > checking sys/file.h presence... yes
> > checking for sys/file.h... yes
> > checking for stdlib.h... (cached) yes
> > checking sys/select.h usability... yes
> > checking sys/select.h presence... yes
> > checking for sys/select.h... yes
> > checking that generated files are newer than configure... done
> > configure: creating ./config.status
> > config.status: creating Makefile
> > config.status: creating doc/Makefile
> > config.status: creating src/Makefile
> > config.status: creating config.h
> > config.status: executing depfiles commands
> > fping-4.2 · (master) ★  ⟩ make                                                                /t/b/fping-4.2
> > make  all-recursive
> > make[1]: 进入目录“/tmp/better-cloudflare-ip/fping-4.2”
> > Making all in doc
> > make[2]: 进入目录“/tmp/better-cloudflare-ip/fping-4.2/doc”
> > make[2]: 对“all”无需做任何事。
> > make[2]: 离开目录“/tmp/better-cloudflare-ip/fping-4.2/doc”
> > Making all in src
> > make[2]: 进入目录“/tmp/better-cloudflare-ip/fping-4.2/src”
> > gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-fping.o -MD -MP -MF .deps/fping-fping.Tpo -c -o fping-fping.o `test -f 'fping.c' || echo './'`fping.c
> > fping.c: 在函数‘sprint_tm’中:
> > fping.c:2599:28: 警告：‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
> > 2599 |         sprintf(buf, "%d.%d", t / 100, (t % 100) / 10);
> > |                            ^
> > fping.c:2599:9: 附注：‘sprintf’ output between 4 and 11 bytes into a destination of size 10
> > 2599 |         sprintf(buf, "%d.%d", t / 100, (t % 100) / 10);
> > |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > fping.c:2595:26: 警告：‘%02d’ directive writing 2 bytes into a region of size between 1 and 8 [-Wformat-overflow=]
> > 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
> > |                          ^~~~
> > fping.c:2595:22: 附注：directive argument in the range [0, 99]
> > 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
> > |                      ^~~~~~~~~
> > fping.c:2595:9: 附注：‘sprintf’ output between 5 and 12 bytes into a destination of size 10
> > 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
> > |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > fping.c: 在函数‘add_name’中:
> > fping.c:2340:82: 警告：‘)’ directive output may be truncated writing 1 byte into a region of size between 0 and 510 [-Wformat-truncation=]
> > 2340 |                 snprintf(nameaddrbuf, sizeof(nameaddrbuf) / sizeof(char), "%s (%s)", printname, addrbuf);
> > |                                                                                  ^
> > fping.c:2340:17: 附注：‘snprintf’ output between 4 and 514 bytes into a destination of size 512
> > 2340 |                 snprintf(nameaddrbuf, sizeof(nameaddrbuf) / sizeof(char), "%s (%s)", printname, addrbuf);
> > |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> > mv -f .deps/fping-fping.Tpo .deps/fping-fping.Po
> > gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-seqmap.o -MD -MP -MF .deps/fping-seqmap.Tpo -c -o fping-seqmap.o `test -f 'seqmap.c' || echo './'`seqmap.c
> > mv -f .deps/fping-seqmap.Tpo .deps/fping-seqmap.Po
> > gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket4.o -MD -MP -MF .deps/fping-socket4.Tpo -c -o fping-socket4.o `test -f 'socket4.c' || echo './'`socket4.c
> > mv -f .deps/fping-socket4.Tpo .deps/fping-socket4.Po
> > gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-optparse.o -MD -MP -MF .deps/fping-optparse.Tpo -c -o fping-optparse.o `test -f 'optparse.c' || echo './'`optparse.c
> > mv -f .deps/fping-optparse.Tpo .deps/fping-optparse.Po
> > gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket6.o -MD -MP -MF .deps/fping-socket6.Tpo -c -o fping-socket6.o `test -f 'socket6.c' || echo './'`socket6.c
> > mv -f .deps/fping-socket6.Tpo .deps/fping-socket6.Po
> > gcc -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2   -o fping fping-fping.o fping-seqmap.o fping-socket4.o fping-optparse.o fping-socket6.o
> > /usr/bin/ld: fping-socket4.o:/tmp/better-cloudflare-ip/fping-4.2/src/fping.h:14: multiple definition of `random_data_flag'; fping-fping.o:/tmp/better-cloudflare-ip/fping-4.2/src/fping.h:14: first defined here /usr/bin/ld: fping-socket6.o:/tmp/better-cloudflare-ip/fping-4.2/src/fping.h:14: multiple definition of `random_data_flag'; fping-fping.o:/tmp/better-cloudflare-ip/fping-4.2/src/fping.h:14: first defined here
> > collect2: 错误：ld 返回 1
> > make[2]: *** [Makefile:350：fping] 错误 1
> > make[2]: 离开目录“/tmp/better-cloudflare-ip/fping-4.2/src”
> > make[1]: *** [Makefile:358：all-recursive] 错误 1
> > make[1]: 离开目录“/tmp/better-cloudflare-ip/fping-4.2”
> > make: *** [Makefile:298：all] 错误 2
> > fping-4.2 · (master) ★  ⟩ ld --version                                                      /t/b/fping-4.2 2
> > GNU ld (GNU Binutils) 2.35
> > Copyright (C) 2020 Free Software Foundation, Inc.
> > 这个程序是自由软件；您可以遵循GNU 通用公共授权版本 3 或
> > (您自行选择的) 稍后版本以再次散布它。
> > 这个程序完全没有任何担保。
> > fping-4.2 · (master) ★  ⟩ gcc --version                                                       /t/b/fping-4.2
> > gcc (GCC) 10.2.0
> > Copyright © 2020 Free Software Foundation, Inc.
> > 本程序是自由软件；请参看源代码的版权声明。本软件没有任何担保；
> > 包括没有适销性和某一专用目的下的适用性担保。
> 
> gcc: 10.2.0
> ld: 2.35

不要使用这样的方式进行配置编译环境   ./configure /t/b/fping-4.2
直接cd到fping-4.2的目录执行编译，严格按照教程来吧

**Comment by IsoaSFlus** [comment]
严格按照教程的步骤来的，还是一样的报错

**Comment by sukanka** [comment]
我也遇到了一样的问题,完全按照步骤来的。
<details>
<summary>错误信息</summary>

```
➜  fping-4.2 ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for netinet/icmp6.h... yes
checking whether SO_TIMESTAMP is declared... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/bin/sh: /home/sukanka/missing: No such file or directory
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for style of include used by make... GNU
checking whether make supports nested variables... yes
checking dependency style of gcc... gcc3
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking whether gcc understands -c and -o together... (cached) yes
checking for gcc option to accept ISO C99... none needed
checking for gcc option to accept ISO Standard C... (cached) none needed
checking how to run the C preprocessor... gcc -E
checking for gethostbyname... yes
checking for connect... yes
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for unistd.h... (cached) yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking for stdlib.h... (cached) yes
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating doc/Makefile
config.status: creating src/Makefile
config.status: creating config.h
config.status: executing depfiles commands
➜  fping-4.2 make
make  all-recursive
make[1]: 进入目录“/home/sukanka/Downloads/fping-4.2”
Making all in doc
make[2]: 进入目录“/home/sukanka/Downloads/fping-4.2/doc”
make[2]: 对“all”无需做任何事。
make[2]: 离开目录“/home/sukanka/Downloads/fping-4.2/doc”
Making all in src
make[2]: 进入目录“/home/sukanka/Downloads/fping-4.2/src”
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-fping.o -MD -MP -MF .deps/fping-fping.Tpo -c -o fping-fping.o `test -f 'fping.c' || echo './'`fping.c
fping.c: 在函数‘sprint_tm’中:
fping.c:2599:28: 警告：‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
 2599 |         sprintf(buf, "%d.%d", t / 100, (t % 100) / 10);
      |                            ^
fping.c:2599:9: 附注：‘sprintf’ output between 4 and 11 bytes into a destination of size 10
 2599 |         sprintf(buf, "%d.%d", t / 100, (t % 100) / 10);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fping.c:2595:26: 警告：‘%02d’ directive writing 2 bytes into a region of size between 1 and 8 [-Wformat-overflow=]
 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
      |                          ^~~~
fping.c:2595:22: 附注：directive argument in the range [0, 99]
 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
      |                      ^~~~~~~~~
fping.c:2595:9: 附注：‘sprintf’ output between 5 and 12 bytes into a destination of size 10
 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fping.c: 在函数‘add_name’中:
fping.c:2340:82: 警告：‘)’ directive output may be truncated writing 1 byte into a region of size between 0 and 510 [-Wformat-truncation=]
 2340 |                 snprintf(nameaddrbuf, sizeof(nameaddrbuf) / sizeof(char), "%s (%s)", printname, addrbuf);
      |                                                                                  ^
fping.c:2340:17: 附注：‘snprintf’ output between 4 and 514 bytes into a destination of size 512
 2340 |                 snprintf(nameaddrbuf, sizeof(nameaddrbuf) / sizeof(char), "%s (%s)", printname, addrbuf);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/fping-fping.Tpo .deps/fping-fping.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-seqmap.o -MD -MP -MF .deps/fping-seqmap.Tpo -c -o fping-seqmap.o `test -f 'seqmap.c' || echo './'`seqmap.c
mv -f .deps/fping-seqmap.Tpo .deps/fping-seqmap.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket4.o -MD -MP -MF .deps/fping-socket4.Tpo -c -o fping-socket4.o `test -f 'socket4.c' || echo './'`socket4.c
mv -f .deps/fping-socket4.Tpo .deps/fping-socket4.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-optparse.o -MD -MP -MF .deps/fping-optparse.Tpo -c -o fping-optparse.o `test -f 'optparse.c' || echo './'`optparse.c
mv -f .deps/fping-optparse.Tpo .deps/fping-optparse.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket6.o -MD -MP -MF .deps/fping-socket6.Tpo -c -o fping-socket6.o `test -f 'socket6.c' || echo './'`socket6.c
mv -f .deps/fping-socket6.Tpo .deps/fping-socket6.Po
gcc -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2   -o fping fping-fping.o fping-seqmap.o fping-socket4.o fping-optparse.o fping-socket6.o  
/usr/bin/ld: fping-socket4.o:/home/sukanka/Downloads/fping-4.2/src/fping.h:14: multiple definition of `random_data_flag'; fping-fping.o:/home/sukanka/Downloads/fping-4.2/src/fping.h:14: first defined here
/usr/bin/ld: fping-socket6.o:/home/sukanka/Downloads/fping-4.2/src/fping.h:14: multiple definition of `random_data_flag'; fping-fping.o:/home/sukanka/Downloads/fping-4.2/src/fping.h:14: first defined here
collect2: 错误：ld 返回 1
make[2]: *** [Makefile:350：fping] 错误 1
make[2]: 离开目录“/home/sukanka/Downloads/fping-4.2/src”
make[1]: *** [Makefile:358：all-recursive] 错误 1
make[1]: 离开目录“/home/sukanka/Downloads/fping-4.2”
make: *** [Makefile:298：all] 错误 2
```
</details>

## 系统信息

<details>
<summary>System Info</summary>

```
➜  ~ neofetch --off
sukanka@asustx 
-------------- 
OS: Arch Linux x86_64 
Host: TUF Gaming FA506IV_FA506IV 1.0 
Kernel: 5.8.6-arch1-1 
Uptime: 1 day, 4 hours 
Packages: 1352 (pacman) 
Shell: zsh 5.8 
Resolution: 1920x1080 
DE: Plasma 
WM: KWin 
WM Theme: Breeze 
Theme: Breeze [Plasma], Breeze [GTK2/3] 
Icons: [Plasma], breeze [GTK2/3] 
Terminal: yakuake 
CPU: AMD Ryzen 7 4800H with Radeon Graphics (16) @ 2.900GHz 
GPU: NVIDIA GeForce RTX 2060 Mobile 
GPU: AMD ATI 06:00.0 Renoir 
Memory: 4392MiB / 63733MiB 
```
</details>

<details>
<summary>gcc</summary>

```
➜  ~ gcc -v
使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
目标：x86_64-pc-linux-gnu
配置为：/build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++,d --with-isl --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-install-libiberty --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-libunwind-exceptions --disable-werror gdc_include_dir=/usr/include/dlang/gdc
线程模型：posix
Supported LTO compression algorithms: zlib zstd
gcc 版本 10.2.0 (GCC) 
```
</details>

<details>
<summary>make</summary>

```
➜  ~ make -v      
GNU Make 4.3
为 x86_64-pc-linux-gnu 编译
Copyright (C) 1988-2020 Free Software Foundation, Inc.
许可证：GPLv3+：GNU 通用公共许可证第 3 版或更新版本<http://gnu.org/licenses/gpl.html>。
本软件是自由软件：您可以自由修改和重新发布它。
在法律允许的范围内没有其他保证。
```
</details>

<details>
<summary>ld</summary>

```
➜  ~ ld --version
GNU ld (GNU Binutils) 2.35
Copyright (C) 2020 Free Software Foundation, Inc.
这个程序是自由软件；您可以遵循GNU 通用公共授权版本 3 或
(您自行选择的) 稍后版本以再次散布它。
这个程序完全没有任何担保。

```
</details>

**Comment by badafans** [comment]
> fping.h:14: multiple definition of `random_data_flag';

https://github.com/schweikert/fping/issues/166  参考fping官方issue，有跟你类似的错误和解决方案

**Comment by sukanka** [comment]
> > fping.h:14: multiple definition of `random_data_flag';
> 
> [schweikert/fping#166](https://github.com/schweikert/fping/issues/166) 参考fping官方issue，有跟你类似的错误和解决方案

感谢， 把 `fping.h` 的 14 行加上 `extern` 就成功了
```c++
 extern int random_data_flag;
```

**Comment by lyrielau** [comment]
sukanka commented on 7 Sep 2020 
的方法解决了
