### ISSUE TITLE
请教下怎样按数据中心来选IP

### ISSUE THREAD

**Issue by zqs125** [badafans/better-cloudflare-ip#72]
比如我想要欧洲的最优IP，怎样弄才能只选欧洲的？

**Comment by badafans** [comment]
这个IP是我服务端下发的，这段时间打算修改服务端下发逻辑，让不同运营商获取指定优化地区的IP

**Comment by zqs125** [comment]
期待你的新版本，我现在需要欧洲的IP，可怎么选都是美国的，没办法选择欧洲的IP，要是能解决自定义数据中心就好了
