### ISSUE TITLE
本人提一个自动化更高的方案

### ISSUE THREAD

**Issue by issacqin** [badafans/better-cloudflare-ip#73]
其实，目前提速根本的途径是找线路入口问题，本人提一个自动化更高的方案，就是利用多个DDNS，指向多个优选IP的，个人已经尝试修改脚本文件，将优选的IP指向一组域名，可以成功，几分钟就可以生效，这样做的好处是，不用再手工操作，直接用域名作为设置，PC端，移动端都可以使用了。

而且，这样做等于可以做成多线路备份，在有“自动选择”功能软件，如WinXray，Clash中，自动会找到优选中的优选进行连接，如速度不理想，也可改为手动模式。一般“自动选择”不推荐，因为会被访问网站会认为访问者是黑客入侵，但是更换线路只是CF入口地址，目标服务器没有变，出口也是同一个，所以没有影响。

我使用了changeip的DDNS解析，接口简单，生效很快。如果采纳方案，请在大作中保留以下申请入口，谢谢：https://www.changeip.com/accounts/aff.php?aff=3799

changeip API：
curl "https://nic.changeip.com/nic/update?cmd=update&u=%UID%&p=%PWD%&hostname=%DDNS_Name%&ip=xxx.xxx.xxx.xxx"

**Comment by badafans** [comment]
你这是为了代理而开发，我这个项目是用来优化网络相关，至于你说的个性化功能不会加入到发布的脚本里面。个性化需求自己去修改相关脚本
