### ISSUE TITLE
最近这速度怎么回事

### ISSUE THREAD

**Issue by DiamondUser** [badafans/better-cloudflare-ip#75]
最近这Cloudflare的速度比之前慢了好多，测了好久也不到400kb/s,之前至少能满足20Mbps带宽需求
![屏幕截图 2021-03-21 142512](https://user-images.githubusercontent.com/64264689/111895998-78e21a80-8a51-11eb-9acb-66b4fe67f748.png)

**Comment by badafans** [comment]
什么运营商

**Comment by DiamondUser** [comment]
电信

**Comment by DiamondUser** [comment]
这速度正常吗

**Comment by badafans** [comment]
要看地区

**Comment by DiamondUser** [comment]
之前都能2000kb/s左右的

**Comment by DiamondUser** [comment]
也就两月份的时候就突然变慢了

**Comment by KimiBear** [comment]
问题解决了吗？
