### ISSUE TITLE
丢包率测试bug

### ISSUE THREAD

**Issue by xkh01** [badafans/better-cloudflare-ip#76]
丢包率测试有bug，ping延迟值没法测，延迟会从0ms到本次测速结束。

**Comment by badafans** [comment]
什么平台的版本

**Comment by xkh01** [comment]
> 什么平台的版本

Windows的，最新版，所有ip的延迟都是从0ms到994ms，也就是说没有计算延迟，ping.csv的文件也是如此

**Comment by badafans** [comment]
不存在你说的这个问题  如果需要详细描述  加入tg群反馈

**Comment by xkh01** [comment]
> 不存在你说的这个问题 如果需要详细描述 加入tg群反馈
问题已解决
