### ISSUE TITLE
debian10编译失败

### ISSUE THREAD

**Issue by lyrielau** [badafans/better-cloudflare-ip#77]
老大什么原因呀
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:350：fping] 错误 1
make[2]: 离开目录“/home/simon/better-cloudflare-ip/linux/src”
make[1]: *** [Makefile:358：all-recursive] 错误 1
make[1]: 离开目录“/home/simon/better-cloudflare-ip/linux”
make: *** [Makefile:298：all] 错误 2

**Comment by badafans** [comment]
https://github.com/badafans/better-cloudflare-ip/issues/7
