### ISSUE TITLE
把cf.sh里的443全改为8443后结果有很大差异

### ISSUE THREAD

**Issue by NP-Prob** [badafans/better-cloudflare-ip#80]
有个问题想请教一下大佬，是否支持对8443端口的测速？
看上去貌似是可以的，将cf.sh里的443全改为8443后脚本仍然正常运行了，但是为何同一台机器上选出的IP不但地理位置差异巨大，而且连接速度也差异很大？

**Comment by badafans** [comment]
改8443回源应该不正常，我服务器没有开8443

**Comment by NP-Prob** [comment]
> 改8443回源应该不正常，我服务器没有开8443

原来如此，不过竟然还能运行，也是挺意外的。能麻烦您开个8443端口么？现在不方便用443了. : (
