### ISSUE TITLE
新版本報病毒？

### ISSUE THREAD

**Issue by panmzh** [badafans/better-cloudflare-ip#81]

**Comment by badafans** [comment]
不存在此类问题

**Comment by Jacobax** [comment]
> 不存在此类问题

win10 WD报毒, 允许后解压有乱码, 但是能用
![image](https://user-images.githubusercontent.com/23228895/114272777-0f4e9e00-9a4a-11eb-8040-56d3bc8ce0f0.png)

**Comment by holefrog** [comment]
旧版本搜索不出来合适的ip了。
新版本win10 确实报病毒。
![Screenshot 2021-04-17 114945](https://user-images.githubusercontent.com/17289895/115100968-207c3b00-9f73-11eb-9f7c-612e78448cef.jpg)

**Comment by panmzh** [comment]
> 舊版本搜索不出來合適的ip了。
> 新版本win10確實報病毒。
> ![Screenshot 2021-04-17 114945](https://user-images.githubusercontent.com/17289895/115100968-207c3b00-9f73-11eb-9f7c-612e78448cef.jpg)

**Comment by holefrog** [comment]
?

**Comment by badafans** [comment]
> > 不存在此类问题
> 
> win10 WD报毒, 允许后解压有乱码, 但是能用
> ![image](https://user-images.githubusercontent.com/23228895/114272777-0f4e9e00-9a4a-11eb-8040-56d3bc8ce0f0.png)

下载release里面的文件

**Comment by holefrog** [comment]
换一台电脑还是报有病毒
<img width="960" alt="1" src="https://user-images.githubusercontent.com/17289895/115642979-817a8900-a34e-11eb-82ff-7a94a603f560.png">
<img width="941" alt="2" src="https://user-images.githubusercontent.com/17289895/115642982-83444c80-a34e-11eb-8926-17bbe47053ab.png">

**Comment by badafans** [comment]
微软自带杀毒是监测下载链接的url的，这个项目被列入黑名单，自然也就报毒。其实都是脚本文件，有没有病毒一看就知道了。没必要纠结杀软的判定结果
