### ISSUE TITLE
archlinux下make命令出错！

### ISSUE THREAD

**Issue by sjkhsl** [badafans/better-cloudflare-ip#83]
make  all-recursive
make[1]: 进入目录“/home/sjkhsl/Downloads/linux”
Making all in doc
make[2]: 进入目录“/home/sjkhsl/Downloads/linux/doc”
make[2]: 对“all”无需做任何事。
make[2]: 离开目录“/home/sjkhsl/Downloads/linux/doc”
Making all in src
make[2]: 进入目录“/home/sjkhsl/Downloads/linux/src”
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-fping.o -MD -MP -MF .deps/fping-fping.Tpo -c -o fping-fping.o `test -f 'fping.c' || echo './'`fping.c
fping.c: 在函数‘sprint_tm’中:
fping.c:2599:28: 警告：‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
 2599 |         sprintf(buf, "%d.%d", t / 100, (t % 100) / 10);
      |                            ^
fping.c:2599:9: 附注：‘sprintf’ output between 4 and 11 bytes into a destination of size 10
 2599 |         sprintf(buf, "%d.%d", t / 100, (t % 100) / 10);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fping.c:2595:26: 警告：‘%02d’ directive writing 2 bytes into a region of size between 1 and 8 [-Wformat-overflow=]
 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
      |                          ^~~~
fping.c:2595:22: 附注：directive argument in the range [0, 99]
 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
      |                      ^~~~~~~~~
fping.c:2595:9: 附注：‘sprintf’ output between 5 and 12 bytes into a destination of size 10
 2595 |         sprintf(buf, "%d.%02d", t / 100, t % 100);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fping.c: 在函数‘add_name’中:
fping.c:2340:82: 警告：‘)’ directive output may be truncated writing 1 byte into a region of size between 0 and 510 [-Wformat-truncation=]
 2340 |                 snprintf(nameaddrbuf, sizeof(nameaddrbuf) / sizeof(char), "%s (%s)", printname, addrbuf);
      |                                                                                  ^
fping.c:2340:17: 附注：‘snprintf’ output between 4 and 514 bytes into a destination of size 512
 2340 |                 snprintf(nameaddrbuf, sizeof(nameaddrbuf) / sizeof(char), "%s (%s)", printname, addrbuf);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
mv -f .deps/fping-fping.Tpo .deps/fping-fping.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-seqmap.o -MD -MP -MF .deps/fping-seqmap.Tpo -c -o fping-seqmap.o `test -f 'seqmap.c' || echo './'`seqmap.c
mv -f .deps/fping-seqmap.Tpo .deps/fping-seqmap.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket4.o -MD -MP -MF .deps/fping-socket4.Tpo -c -o fping-socket4.o `test -f 'socket4.c' || echo './'`socket4.c
mv -f .deps/fping-socket4.Tpo .deps/fping-socket4.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-optparse.o -MD -MP -MF .deps/fping-optparse.Tpo -c -o fping-optparse.o `test -f 'optparse.c' || echo './'`optparse.c
mv -f .deps/fping-optparse.Tpo .deps/fping-optparse.Po
gcc -DHAVE_CONFIG_H -I. -I..    -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2 -MT fping-socket6.o -MD -MP -MF .deps/fping-socket6.Tpo -c -o fping-socket6.o `test -f 'socket6.c' || echo './'`socket6.c
mv -f .deps/fping-socket6.Tpo .deps/fping-socket6.Po
gcc -Wall -Wextra -Wno-sign-compare -DIPV6 -g -O2   -o fping fping-fping.o fping-seqmap.o fping-socket4.o fping-optparse.o fping-socket6.o  
/usr/bin/ld: fping-socket4.o:/home/sjkhsl/Downloads/linux/src/fping.h:14: multiple definition of `random_data_flag'; fping-fping.o:/home/sjkhsl/Downloads/linux/src/fping.h:14: first defined here
/usr/bin/ld: fping-socket6.o:/home/sjkhsl/Downloads/linux/src/fping.h:14: multiple definition of `random_data_flag'; fping-fping.o:/home/sjkhsl/Downloads/linux/src/fping.h:14: first defined here
collect2: 错误：ld 返回 1
make[2]: *** [Makefile:350：fping] 错误 1
make[2]: 离开目录“/home/sjkhsl/Downloads/linux/src”
make[1]: *** [Makefile:358：all-recursive] 错误 1
make[1]: 离开目录“/home/sjkhsl/Downloads/linux”
make: *** [Makefile:298：all] 错误 2

**Comment by badafans** [comment]
参考已经关闭的issue

**Comment by qwIvan** [comment]
> 参考已经关闭的issue

那么到底参考哪个呢。。
