### ISSUE TITLE
指定ip地址

### ISSUE THREAD

**Issue by googbad** [badafans/better-cloudflare-ip#84]
可以只测试香港的ip地址池吗？从里面挑选

**Comment by badafans** [comment]
现在移动网络环境下下发的都是HKG的IP，是服务端自动识别处理的

**Comment by googbad** [comment]
我家里是联通的宽带，有实现方式吗？之前匹配出来的香港ip速度都很快，现在匹配的基本都是美国ip，测速很快实际很慢。

**Comment by badafans** [comment]
> 

联通没有接入CF的香港机房
