### ISSUE TITLE
CF ip选优是否已经无法为VPS连接提供加速了？

### ISSUE THREAD

**Issue by Aspreadfire** [badafans/better-cloudflare-ip#85]
从本月开始，在移动网络下，使用www.cloudflare.com + head=“VPS网址”的方式实测无法通过WS连接到VPS了，报错：
(wss://cloudflare.com/path): 403 Forbidden > websocket: bad handshake] > common/retry: all retry attempts failed

ip选优筛选出的ip实测也会产生相同报错(wss://选优ip/path): 403 Forbidden > websocket: bad handshake] > common/retry: all retry attempts failed

![image](https://user-images.githubusercontent.com/55733912/115152121-6ab00a00-a0a2-11eb-8d89-674203bba9f4.png)
这是之前的连接设置

现在使用CDN加速必须在连接中直接指定连接地址为“VPS网址”。
![image](https://user-images.githubusercontent.com/55733912/115152171-99c67b80-a0a2-11eb-9fb3-cc5a27638048.png)

不知道这种情况是个例吗？这是否意味着CF自选IP已经无法被应用在VPS连接的CDN加速上了？

**Comment by badafans** [comment]
此issue不提供代理方面的解答
