### ISSUE TITLE
openwrt 代理模式切换

### ISSUE THREAD

**Issue by hugecocks** [badafans/better-cloudflare-ip#86]
openwrt中，为了准确筛选适合本地网络的IP，能否增加一个流程，让脚本执行前强制切换到直连模式，筛选出IP后在回复原有模式？

**Comment by badafans** [comment]
添加cf ip白名单就行了  不必要搞的这么麻烦

103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
104.16.0.0/13
104.24.0.0/14
108.162.192.0/18
131.0.72.0/22
141.101.64.0/18
162.158.0.0/15
172.64.0.0/13
173.245.48.0/20
188.114.96.0/20
190.93.240.0/20
197.234.240.0/22
198.41.128.0/17
1.0.0.0/24
1.1.1.0/24

**Comment by Biercenter** [comment]
之前我也是添加到直连，偶尔还是会被代理，或者导致有些网络编程直连无法打开，现在我用uci关闭ssrp然后测试完IP，自动替换到ssrp的服务器地址再开启代理，uci就是命令行修改配置的工具，openwrt官网或者谷歌一下就有教程，很简单的。
