### ISSUE TITLE
openwrt上运行脚本后无法正常测速并输出，一直循环（anycast.txt文件里的ip已经符合带宽要求的情况下）

### ISSUE THREAD

**Issue by anshifa958** [badafans/better-cloudflare-ip#87]
在windows上运行正常，但是在openwrt上无法正常运行，运行情况为：

104.20.165.58 启动测速
104.21.95.225 启动测速
等待测速进程结束,筛选出三个优选的IP
测速完成
指向解析获取CF节点IP
-=O#-  #     #       #                                                                                                                                       
正在测试 ICMP 丢包率:进程数 1,已完成 0 %
正在测试 ICMP 丢包率:进程数 2,已完成 1 %

一直这样循环下去

**Comment by badafans** [comment]
部分openwrt上的用的命令不是标准gun工具，导致文件下载没有在对应目录生成

**Comment by anshifa958** [comment]
好的，谢谢解答

**Comment by xdfx1180** [comment]
> 部分openwrt上的用的命令不是标准gun工具，导致文件下载没有在对应目录生成

那在不换openwrt固件的情形下，如何解决呢？

**Comment by badafans** [comment]
目前最新版已经完美兼容OP

**Comment by anshifa958** [comment]
您好，我已经收到了你的来信，我将尽快回复你
