### ISSUE TITLE
要多长时间才能测试完成

### ISSUE THREAD

**Issue by BakerJrr** [badafans/better-cloudflare-ip#90]
一直在循环
![C613612A-0063-4768-96BA-EB129202D2F9](https://user-images.githubusercontent.com/58174744/118291224-eb2f2280-b509-11eb-98a0-ae6817bf3b0b.png)

**Comment by badafans** [comment]
说明你的当前环境有问题，正常四十多秒

**Comment by fredericky123** [comment]
一样的网络环境，mac下1min以内出结果，win 10却不断循环，报错如图，是什么配置不对么
![image](https://user-images.githubusercontent.com/13982749/131271174-31972ef0-0061-4273-8ce5-06e034c2cc74.png)

**Comment by fredericky123** [comment]
@badafans 请问上述错误正常么

**Comment by badafans** [comment]
> @badafans 请问上述错误正常么

请用最新版本试试
