### ISSUE TITLE
能否对目前ip先进行测速，不满足后再优选

### ISSUE THREAD

**Issue by jeff-mao** [badafans/better-cloudflare-ip#96]

**Comment by badafans** [comment]
不如直接优选来得快，如果这个IP足够优秀，还是会再次找到它的

**Comment by Asrielwiki** [comment]
我觉得没有必要，不如直接优选。因为你通过目前ip进行科学上网的时候，其实已经在测速了，另外，既然你都要对ip进行优选，说明当前ip已经不满足你的要求了
